// ================================================================
// PP 22/2021 — Baku Mutu Lingkungan (Environmental Quality Standards)
// Lampiran VI  : Baku Mutu Air Nasional (I. Sungai · II. Danau)
// Lampiran VII : Baku Mutu Udara Ambien
// Lampiran VIII: Baku Mutu Air Laut
// Values transcribed from the official PDF (pdftotext -table mode) and
// cross-checked parameter-by-parameter against the regulation text.
// Labels carried in 3 languages: i = Bahasa Indonesia (authoritative
// legal term) / e = English / z = 简体中文.
// Every table is exportable to Excel via exportEnvTable().
// ================================================================
window.ENV_TABLES = {

river:{
  code:"PP 22/2021 Lampiran VI-I",
  title:{i:"Baku Mutu Air Sungai dan Sejenisnya",e:"River Water Quality Standard",z:"河流及类似水体水质标准"},
  cols:{i:["No","Parameter","Satuan","Kelas I","Kelas II","Kelas III","Kelas IV","Keterangan"],
        e:["No","Parameter","Unit","Class I","Class II","Class III","Class IV","Remarks"],
        z:["序号","参数","单位","I 类","II 类","III 类","IV 类","备注"]},
  rows:[
   {n:"1",p:{i:"Temperatur",e:"Temperature",z:"水温"},u:"°C",v:["Dev 3","Dev 3","Dev 3","Dev 3"],k:{i:"Perbedaan dengan suhu udara di atas permukaan air",e:"Deviation from air temperature above the water surface",z:"与水面上方气温的偏差"}},
   {n:"2",p:{i:"Padatan terlarut total (TDS)",e:"Total Dissolved Solids (TDS)",z:"总溶解固体 (TDS)"},u:"mg/L",v:["1.000","1.000","1.000","2.000"],k:{i:"Tidak berlaku untuk muara",e:"Not applicable to estuaries",z:"不适用于河口"}},
   {n:"3",p:{i:"Padatan tersuspensi total (TSS)",e:"Total Suspended Solids (TSS)",z:"总悬浮物 (TSS)"},u:"mg/L",v:["40","50","100","400"],k:{i:"",e:"",z:""}},
   {n:"4",p:{i:"Warna",e:"Colour",z:"色度"},u:"Pt-Co Unit",v:["15","50","100","—"],k:{i:"Tidak berlaku untuk air gambut (berdasarkan kondisi alaminya)",e:"Not applicable to peat water (based on its natural condition)",z:"不适用于泥炭水（按其天然状态）"}},
   {n:"5",p:{i:"Derajat keasaman (pH)",e:"Acidity (pH)",z:"pH 值"},u:"—",v:["6-9","6-9","6-9","6-9"],k:{i:"Tidak berlaku untuk air gambut (berdasarkan kondisi alaminya)",e:"Not applicable to peat water (based on its natural condition)",z:"不适用于泥炭水（按其天然状态）"}},
   {n:"6",p:{i:"Kebutuhan oksigen biokimiawi (BOD)",e:"Biochemical Oxygen Demand (BOD)",z:"生化需氧量 (BOD)"},u:"mg/L",v:["2","3","6","12"],k:{i:"",e:"",z:""}},
   {n:"7",p:{i:"Kebutuhan oksigen kimiawi (COD)",e:"Chemical Oxygen Demand (COD)",z:"化学需氧量 (COD)"},u:"mg/L",v:["10","25","40","80"],k:{i:"",e:"",z:""}},
   {n:"8",p:{i:"Oksigen terlarut (DO)",e:"Dissolved Oxygen (DO)",z:"溶解氧 (DO)"},u:"mg/L",v:["6","4","3","1"],k:{i:"Batas minimal",e:"Minimum limit",z:"最低限值"}},
   {n:"9",p:{i:"Sulfat (SO₄²⁻)",e:"Sulphate (SO₄²⁻)",z:"硫酸盐 (SO₄²⁻)"},u:"mg/L",v:["300","300","300","400"],k:{i:"",e:"",z:""}},
   {n:"10",p:{i:"Klorida (Cl⁻)",e:"Chloride (Cl⁻)",z:"氯化物 (Cl⁻)"},u:"mg/L",v:["300","300","300","600"],k:{i:"",e:"",z:""}},
   {n:"11",p:{i:"Nitrat (sebagai N)",e:"Nitrate (as N)",z:"硝酸盐（以 N 计）"},u:"mg/L",v:["10","10","20","20"],k:{i:"",e:"",z:""}},
   {n:"12",p:{i:"Nitrit (sebagai N)",e:"Nitrite (as N)",z:"亚硝酸盐（以 N 计）"},u:"mg/L",v:["0,06","0,06","0,06","—"],k:{i:"Bagi air baku air minum tidak dipersyaratkan",e:"Not required where used as drinking-water raw water",z:"作为饮用水源水时不作要求"}},
   {n:"13",p:{i:"Amoniak (sebagai N)",e:"Ammonia (as N)",z:"氨氮（以 N 计）"},u:"mg/L",v:["0,1","0,2","0,5","—"],k:{i:"",e:"",z:""}},
   {n:"14",p:{i:"Total Nitrogen",e:"Total Nitrogen",z:"总氮"},u:"mg/L",v:["15","15","25","—"],k:{i:"",e:"",z:""}},
   {n:"15",p:{i:"Total Fosfat (sebagai P)",e:"Total Phosphate (as P)",z:"总磷（以 P 计）"},u:"mg/L",v:["0,2","0,2","1","—"],k:{i:"",e:"",z:""}},
   {n:"16",p:{i:"Fluorida (F⁻)",e:"Fluoride (F⁻)",z:"氟化物 (F⁻)"},u:"mg/L",v:["1","1,5","1,5","—"],k:{i:"",e:"",z:""}},
   {n:"17",p:{i:"Belerang sebagai H₂S",e:"Sulphide as H₂S",z:"硫化物（以 H₂S 计）"},u:"mg/L",v:["0,002","0,002","0,002","—"],k:{i:"",e:"",z:""}},
   {n:"18",p:{i:"Sianida (CN⁻)",e:"Cyanide (CN⁻)",z:"氰化物 (CN⁻)"},u:"mg/L",v:["0,02","0,02","0,02","—"],k:{i:"",e:"",z:""}},
   {n:"19",p:{i:"Klorin bebas",e:"Free Chlorine",z:"游离氯"},u:"mg/L",v:["0,03","0,03","0,03","—"],k:{i:"Bagi air baku air minum tidak dipersyaratkan",e:"Not required where used as drinking-water raw water",z:"作为饮用水源水时不作要求"}},
   {n:"20",p:{i:"Barium (Ba) terlarut",e:"Dissolved Barium (Ba)",z:"溶解性钡 (Ba)"},u:"mg/L",v:["1,0","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"21",p:{i:"Boron (B) terlarut",e:"Dissolved Boron (B)",z:"溶解性硼 (B)"},u:"mg/L",v:["1,0","1,0","1,0","1,0"],k:{i:"",e:"",z:""}},
   {n:"22",p:{i:"Merkuri (Hg) terlarut",e:"Dissolved Mercury (Hg)",z:"溶解性汞 (Hg)"},u:"mg/L",v:["0,001","0,002","0,002","0,005"],k:{i:"",e:"",z:""}},
   {n:"23",p:{i:"Arsen (As) terlarut",e:"Dissolved Arsenic (As)",z:"溶解性砷 (As)"},u:"mg/L",v:["0,05","0,05","0,05","0,10"],k:{i:"",e:"",z:""}},
   {n:"24",p:{i:"Selenium (Se) terlarut",e:"Dissolved Selenium (Se)",z:"溶解性硒 (Se)"},u:"mg/L",v:["0,01","0,05","0,05","0,05"],k:{i:"",e:"",z:""}},
   {n:"25",p:{i:"Besi (Fe) terlarut",e:"Dissolved Iron (Fe)",z:"溶解性铁 (Fe)"},u:"mg/L",v:["0,3","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"26",p:{i:"Kadmium (Cd) terlarut",e:"Dissolved Cadmium (Cd)",z:"溶解性镉 (Cd)"},u:"mg/L",v:["0,01","0,01","0,01","0,01"],k:{i:"",e:"",z:""}},
   {n:"27",p:{i:"Kobalt (Co) terlarut",e:"Dissolved Cobalt (Co)",z:"溶解性钴 (Co)"},u:"mg/L",v:["0,2","0,2","0,2","0,2"],k:{i:"",e:"",z:""}},
   {n:"28",p:{i:"Mangan (Mn) terlarut",e:"Dissolved Manganese (Mn)",z:"溶解性锰 (Mn)"},u:"mg/L",v:["0,1","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"29",p:{i:"Nikel (Ni) terlarut",e:"Dissolved Nickel (Ni)",z:"溶解性镍 (Ni)"},u:"mg/L",v:["0,05","0,05","0,05","0,1"],k:{i:"",e:"",z:""}},
   {n:"30",p:{i:"Seng (Zn) terlarut",e:"Dissolved Zinc (Zn)",z:"溶解性锌 (Zn)"},u:"mg/L",v:["0,05","0,05","0,05","2"],k:{i:"",e:"",z:""}},
   {n:"31",p:{i:"Tembaga (Cu) terlarut",e:"Dissolved Copper (Cu)",z:"溶解性铜 (Cu)"},u:"mg/L",v:["0,02","0,02","0,02","0,2"],k:{i:"",e:"",z:""}},
   {n:"32",p:{i:"Timbal (Pb) terlarut",e:"Dissolved Lead (Pb)",z:"溶解性铅 (Pb)"},u:"mg/L",v:["0,03","0,03","0,03","0,5"],k:{i:"",e:"",z:""}},
   {n:"33",p:{i:"Kromium heksavalen (Cr(VI))",e:"Hexavalent Chromium (Cr(VI))",z:"六价铬 (Cr(VI))"},u:"mg/L",v:["0,05","0,05","0,05","1"],k:{i:"",e:"",z:""}},
   {n:"34",p:{i:"Minyak dan lemak",e:"Oil and Grease",z:"石油类与油脂"},u:"mg/L",v:["1","1","1","10"],k:{i:"",e:"",z:""}},
   {n:"35",p:{i:"Deterjen total",e:"Total Detergent (MBAS)",z:"总洗涤剂 (MBAS)"},u:"mg/L",v:["0,2","0,2","0,2","—"],k:{i:"",e:"",z:""}},
   {n:"36",p:{i:"Fenol",e:"Phenol",z:"酚类"},u:"mg/L",v:["0,002","0,005","0,01","0,02"],k:{i:"",e:"",z:""}},
   {n:"37",p:{i:"Aldrin/Dieldrin",e:"Aldrin/Dieldrin",z:"艾氏剂/狄氏剂"},u:"µg/L",v:["17","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"38",p:{i:"BHC",e:"BHC",z:"六六六 (BHC)"},u:"µg/L",v:["210","210","210","—"],k:{i:"",e:"",z:""}},
   {n:"39",p:{i:"Chlordane",e:"Chlordane",z:"氯丹"},u:"µg/L",v:["3","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"40",p:{i:"DDT",e:"DDT",z:"滴滴涕 (DDT)"},u:"µg/L",v:["2","2","2","2"],k:{i:"",e:"",z:""}},
   {n:"41",p:{i:"Endrin",e:"Endrin",z:"异狄氏剂"},u:"µg/L",v:["1","4","4","—"],k:{i:"",e:"",z:""}},
   {n:"42",p:{i:"Heptachlor",e:"Heptachlor",z:"七氯"},u:"µg/L",v:["18","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"43",p:{i:"Lindane",e:"Lindane",z:"林丹"},u:"µg/L",v:["56","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"44",p:{i:"Methoxychlor",e:"Methoxychlor",z:"甲氧滴滴涕"},u:"µg/L",v:["35","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"45",p:{i:"Toxaphan",e:"Toxaphene",z:"毒杀芬"},u:"µg/L",v:["5","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"46",p:{i:"Fecal Coliform",e:"Faecal Coliform",z:"粪大肠菌群"},u:"MPN/100 mL",v:["100","1.000","2.000","2.000"],k:{i:"",e:"",z:""}},
   {n:"47",p:{i:"Total Coliform",e:"Total Coliform",z:"总大肠菌群"},u:"MPN/100 mL",v:["1.000","5.000","10.000","10.000"],k:{i:"",e:"",z:""}},
   {n:"48",p:{i:"Sampah",e:"Refuse / Litter",z:"垃圾"},u:"—",v:["nihil","nihil","nihil","nihil"],k:{i:"nihil = tidak ada",e:"nihil = none",z:"nihil = 无"}},
   {n:"49",p:{i:"Radioaktivitas — Gross-A",e:"Radioactivity — Gross-α",z:"放射性 — 总 α"},u:"Bq/L",v:["0,1","0,1","0,1","0,1"],k:{i:"",e:"",z:""}},
   {n:"",p:{i:"Radioaktivitas — Gross-B",e:"Radioactivity — Gross-β",z:"放射性 — 总 β"},u:"Bq/L",v:["1","1","1","1"],k:{i:"",e:"",z:""}}
  ]
},

lake:{
  code:"PP 22/2021 Lampiran VI-II",
  title:{i:"Baku Mutu Air Danau dan Sejenisnya",e:"Lake Water Quality Standard",z:"湖泊及类似水体水质标准"},
  cols:{i:["No","Parameter","Satuan","Kelas I","Kelas II","Kelas III","Kelas IV","Keterangan"],
        e:["No","Parameter","Unit","Class I","Class II","Class III","Class IV","Remarks"],
        z:["序号","参数","单位","I 类","II 类","III 类","IV 类","备注"]},
  rows:[
   {n:"1",p:{i:"Temperatur",e:"Temperature",z:"水温"},u:"°C",v:["Dev 3","Dev 3","Dev 3","Dev 3"],k:{i:"Perbedaan dengan suhu udara di atas permukaan air",e:"Deviation from air temperature above the water surface",z:"与水面上方气温的偏差"}},
   {n:"2",p:{i:"Padatan terlarut total (TDS)",e:"Total Dissolved Solids (TDS)",z:"总溶解固体 (TDS)"},u:"mg/L",v:["1.000","1.000","1.000","1.000"],k:{i:"",e:"",z:""}},
   {n:"3",p:{i:"Padatan tersuspensi total (TSS)",e:"Total Suspended Solids (TSS)",z:"总悬浮物 (TSS)"},u:"mg/L",v:["25","50","100","400"],k:{i:"",e:"",z:""}},
   {n:"4",p:{i:"Transparansi",e:"Transparency",z:"透明度"},u:"m",v:["10","4","2,5","—"],k:{i:"",e:"",z:""}},
   {n:"5",p:{i:"Warna",e:"Colour",z:"色度"},u:"Pt-Co Unit",v:["15","50","100","—"],k:{i:"",e:"",z:""}},
   {n:"6",p:{i:"Derajat keasaman (pH)",e:"Acidity (pH)",z:"pH 值"},u:"—",v:["6-9","6-9","6-9","6-9"],k:{i:"Tidak berlaku untuk air gambut (berdasarkan kondisi alaminya)",e:"Not applicable to peat water (based on its natural condition)",z:"不适用于泥炭水（按其天然状态）"}},
   {n:"7",p:{i:"Kebutuhan oksigen biokimiawi (BOD)",e:"Biochemical Oxygen Demand (BOD)",z:"生化需氧量 (BOD)"},u:"mg/L",v:["2","3","6","12"],k:{i:"",e:"",z:""}},
   {n:"8",p:{i:"Kebutuhan oksigen kimiawi (COD)",e:"Chemical Oxygen Demand (COD)",z:"化学需氧量 (COD)"},u:"mg/L",v:["10","25","40","80"],k:{i:"",e:"",z:""}},
   {n:"9",p:{i:"Oksigen terlarut (DO)",e:"Dissolved Oxygen (DO)",z:"溶解氧 (DO)"},u:"mg/L",v:["6","4","3","1"],k:{i:"Batas minimal",e:"Minimum limit",z:"最低限值"}},
   {n:"10",p:{i:"Sulfat (SO₄²⁻)",e:"Sulphate (SO₄²⁻)",z:"硫酸盐 (SO₄²⁻)"},u:"mg/L",v:["300","300","300","400"],k:{i:"",e:"",z:""}},
   {n:"11",p:{i:"Klorida (Cl⁻)",e:"Chloride (Cl⁻)",z:"氯化物 (Cl⁻)"},u:"mg/L",v:["300","300","300","600"],k:{i:"",e:"",z:""}},
   {n:"12",p:{i:"Total Nitrogen",e:"Total Nitrogen",z:"总氮"},u:"mg/L",v:["0,65","0,75","1,90","—"],k:{i:"",e:"",z:""}},
   {n:"13",p:{i:"Total Fosfat (sebagai P)",e:"Total Phosphate (as P)",z:"总磷（以 P 计）"},u:"mg/L",v:["0,01","0,03","0,1","—"],k:{i:"",e:"",z:""}},
   {n:"14",p:{i:"Fluorida (F⁻)",e:"Fluoride (F⁻)",z:"氟化物 (F⁻)"},u:"mg/L",v:["1","1,5","1,5","—"],k:{i:"",e:"",z:""}},
   {n:"15",p:{i:"Belerang sebagai H₂S",e:"Sulphide as H₂S",z:"硫化物（以 H₂S 计）"},u:"mg/L",v:["0,002","0,002","0,002","—"],k:{i:"",e:"",z:""}},
   {n:"16",p:{i:"Sianida (CN⁻)",e:"Cyanide (CN⁻)",z:"氰化物 (CN⁻)"},u:"mg/L",v:["0,02","0,02","0,02","—"],k:{i:"",e:"",z:""}},
   {n:"17",p:{i:"Klorin bebas",e:"Free Chlorine",z:"游离氯"},u:"mg/L",v:["0,03","0,03","0,03","—"],k:{i:"Bagi air baku air minum tidak dipersyaratkan",e:"Not required where used as drinking-water raw water",z:"作为饮用水源水时不作要求"}},
   {n:"18",p:{i:"Barium (Ba) terlarut",e:"Dissolved Barium (Ba)",z:"溶解性钡 (Ba)"},u:"mg/L",v:["1,0","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"19",p:{i:"Boron (B) terlarut",e:"Dissolved Boron (B)",z:"溶解性硼 (B)"},u:"mg/L",v:["1,0","1,0","1,0","1,0"],k:{i:"",e:"",z:""}},
   {n:"20",p:{i:"Merkuri (Hg) terlarut",e:"Dissolved Mercury (Hg)",z:"溶解性汞 (Hg)"},u:"mg/L",v:["0,001","0,002","0,002","0,005"],k:{i:"",e:"",z:""}},
   {n:"21",p:{i:"Arsen (As) terlarut",e:"Dissolved Arsenic (As)",z:"溶解性砷 (As)"},u:"mg/L",v:["0,05","0,05","0,05","0,1"],k:{i:"",e:"",z:""}},
   {n:"22",p:{i:"Selenium (Se) terlarut",e:"Dissolved Selenium (Se)",z:"溶解性硒 (Se)"},u:"mg/L",v:["0,01","0,05","0,05","0,05"],k:{i:"",e:"",z:""}},
   {n:"23",p:{i:"Besi (Fe) terlarut",e:"Dissolved Iron (Fe)",z:"溶解性铁 (Fe)"},u:"mg/L",v:["0,3","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"24",p:{i:"Kadmium (Cd) terlarut",e:"Dissolved Cadmium (Cd)",z:"溶解性镉 (Cd)"},u:"mg/L",v:["0,01","0,01","0,01","0,01"],k:{i:"",e:"",z:""}},
   {n:"25",p:{i:"Kobalt (Co) terlarut",e:"Dissolved Cobalt (Co)",z:"溶解性钴 (Co)"},u:"mg/L",v:["0,2","0,2","0,2","0,2"],k:{i:"",e:"",z:""}},
   {n:"26",p:{i:"Mangan (Mn) terlarut",e:"Dissolved Manganese (Mn)",z:"溶解性锰 (Mn)"},u:"mg/L",v:["0,4","0,4","0,5","1,0"],k:{i:"",e:"",z:""}},
   {n:"27",p:{i:"Nikel (Ni) terlarut",e:"Dissolved Nickel (Ni)",z:"溶解性镍 (Ni)"},u:"mg/L",v:["0,05","0,05","0,05","0,1"],k:{i:"",e:"",z:""}},
   {n:"28",p:{i:"Seng (Zn) terlarut",e:"Dissolved Zinc (Zn)",z:"溶解性锌 (Zn)"},u:"mg/L",v:["0,05","0,05","0,05","2,0"],k:{i:"",e:"",z:""}},
   {n:"29",p:{i:"Tembaga (Cu) terlarut",e:"Dissolved Copper (Cu)",z:"溶解性铜 (Cu)"},u:"mg/L",v:["0,02","0,02","0,02","0,2"],k:{i:"",e:"",z:""}},
   {n:"30",p:{i:"Timbal (Pb) terlarut",e:"Dissolved Lead (Pb)",z:"溶解性铅 (Pb)"},u:"mg/L",v:["0,03","0,03","0,03","0,5"],k:{i:"",e:"",z:""}},
   {n:"31",p:{i:"Kromium heksavalen (Cr(VI))",e:"Hexavalent Chromium (Cr(VI))",z:"六价铬 (Cr(VI))"},u:"mg/L",v:["0,05","0,05","0,05","1"],k:{i:"",e:"",z:""}},
   {n:"32",p:{i:"Minyak dan lemak",e:"Oil and Grease",z:"石油类与油脂"},u:"mg/L",v:["1","1","1","10"],k:{i:"",e:"",z:""}},
   {n:"33",p:{i:"Deterjen total",e:"Total Detergent (MBAS)",z:"总洗涤剂 (MBAS)"},u:"mg/L",v:["0,2","0,2","0,2","—"],k:{i:"",e:"",z:""}},
   {n:"34",p:{i:"Fenol",e:"Phenol",z:"酚类"},u:"mg/L",v:["0,002","0,005","0,01","0,02"],k:{i:"",e:"",z:""}},
   {n:"35",p:{i:"Aldrin/Dieldrin",e:"Aldrin/Dieldrin",z:"艾氏剂/狄氏剂"},u:"µg/L",v:["17","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"36",p:{i:"BHC",e:"BHC",z:"六六六 (BHC)"},u:"µg/L",v:["210","210","210","—"],k:{i:"",e:"",z:""}},
   {n:"37",p:{i:"Chlordane",e:"Chlordane",z:"氯丹"},u:"µg/L",v:["3","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"38",p:{i:"DDT",e:"DDT",z:"滴滴涕 (DDT)"},u:"µg/L",v:["2","2","2","2"],k:{i:"",e:"",z:""}},
   {n:"39",p:{i:"Endrin",e:"Endrin",z:"异狄氏剂"},u:"µg/L",v:["1","4","4","—"],k:{i:"",e:"",z:""}},
   {n:"40",p:{i:"Heptachlor",e:"Heptachlor",z:"七氯"},u:"µg/L",v:["18","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"41",p:{i:"Lindane",e:"Lindane",z:"林丹"},u:"µg/L",v:["56","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"42",p:{i:"Methoxychlor",e:"Methoxychlor",z:"甲氧滴滴涕"},u:"µg/L",v:["35","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"43",p:{i:"Toxaphan",e:"Toxaphene",z:"毒杀芬"},u:"µg/L",v:["5","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"44",p:{i:"Fecal Coliform",e:"Faecal Coliform",z:"粪大肠菌群"},u:"MPN/100 mL",v:["100","1.000","2.000","2.000"],k:{i:"",e:"",z:""}},
   {n:"45",p:{i:"Total Coliform",e:"Total Coliform",z:"总大肠菌群"},u:"MPN/100 mL",v:["1.000","5.000","10.000","10.000"],k:{i:"",e:"",z:""}},
   {n:"46",p:{i:"Klorofil-a",e:"Chlorophyll-a",z:"叶绿素 a"},u:"mg/m³",v:["10","50","100","200"],k:{i:"",e:"",z:""}},
   {n:"47",p:{i:"Sampah",e:"Refuse / Litter",z:"垃圾"},u:"—",v:["nihil","nihil","nihil","nihil"],k:{i:"nihil = tidak ada",e:"nihil = none",z:"nihil = 无"}},
   {n:"48",p:{i:"Radioaktivitas — Gross-A",e:"Radioactivity — Gross-α",z:"放射性 — 总 α"},u:"Bq/L",v:["0,1","0,1","0,1","0,1"],k:{i:"",e:"",z:""}},
   {n:"",p:{i:"Radioaktivitas — Gross-B",e:"Radioactivity — Gross-β",z:"放射性 — 总 β"},u:"Bq/L",v:["1","1","1","1"],k:{i:"",e:"",z:""}}
  ]
},

air:{
  code:"PP 22/2021 Lampiran VII",
  title:{i:"Baku Mutu Udara Ambien",e:"Ambient Air Quality Standard",z:"环境空气质量标准"},
  cols:{i:["No","Parameter","Waktu Pengukuran","Baku Mutu","Sistem Pengukuran"],
        e:["No","Parameter","Averaging Time","Limit Value","Measurement System"],
        z:["序号","参数","测量时段","标准限值","测量方式"]},
  rows:[
   {n:"1",p:{i:"Sulfur Dioksida (SO₂)",e:"Sulphur Dioxide (SO₂)",z:"二氧化硫 (SO₂)"},u:"1 jam|1 hour|1 小时",v:["150 µg/m³"],k:{i:"aktif kontinu / aktif manual",e:"continuous active / manual active",z:"连续自动 / 手工"}},
   {n:"",p:{i:"Sulfur Dioksida (SO₂)",e:"Sulphur Dioxide (SO₂)",z:"二氧化硫 (SO₂)"},u:"24 jam|24 hours|24 小时",v:["75 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"",p:{i:"Sulfur Dioksida (SO₂)",e:"Sulphur Dioxide (SO₂)",z:"二氧化硫 (SO₂)"},u:"1 tahun|1 year|1 年",v:["45 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"2",p:{i:"Karbon Monoksida (CO)",e:"Carbon Monoxide (CO)",z:"一氧化碳 (CO)"},u:"1 jam|1 hour|1 小时",v:["10.000 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"",p:{i:"Karbon Monoksida (CO)",e:"Carbon Monoxide (CO)",z:"一氧化碳 (CO)"},u:"8 jam|8 hours|8 小时",v:["4.000 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"3",p:{i:"Nitrogen Dioksida (NO₂)",e:"Nitrogen Dioxide (NO₂)",z:"二氧化氮 (NO₂)"},u:"1 jam|1 hour|1 小时",v:["200 µg/m³"],k:{i:"aktif kontinu / aktif manual",e:"continuous active / manual active",z:"连续自动 / 手工"}},
   {n:"",p:{i:"Nitrogen Dioksida (NO₂)",e:"Nitrogen Dioxide (NO₂)",z:"二氧化氮 (NO₂)"},u:"24 jam|24 hours|24 小时",v:["65 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"",p:{i:"Nitrogen Dioksida (NO₂)",e:"Nitrogen Dioxide (NO₂)",z:"二氧化氮 (NO₂)"},u:"1 tahun|1 year|1 年",v:["50 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"4",p:{i:"Oksidan fotokimia (Ox) sebagai Ozon (O₃)",e:"Photochemical Oxidants (Ox) as Ozone (O₃)",z:"光化学氧化剂（以臭氧 O₃ 计）"},u:"1 jam|1 hour|1 小时",v:["150 µg/m³"],k:{i:"aktif kontinu / aktif manual #",e:"continuous active / manual active #",z:"连续自动 / 手工 #"}},
   {n:"",p:{i:"Oksidan fotokimia (Ox) sebagai Ozon (O₃)",e:"Photochemical Oxidants (Ox) as Ozone (O₃)",z:"光化学氧化剂（以臭氧 O₃ 计）"},u:"8 jam|8 hours|8 小时",v:["100 µg/m³"],k:{i:"aktif kontinu ##",e:"continuous active ##",z:"连续自动 ##"}},
   {n:"",p:{i:"Oksidan fotokimia (Ox) sebagai Ozon (O₃)",e:"Photochemical Oxidants (Ox) as Ozone (O₃)",z:"光化学氧化剂（以臭氧 O₃ 计）"},u:"1 tahun|1 year|1 年",v:["35 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"5",p:{i:"Hidrokarbon Non Metana (NMHC)",e:"Non-Methane Hydrocarbons (NMHC)",z:"非甲烷总烃 (NMHC)"},u:"3 jam|3 hours|3 小时",v:["160 µg/m³"],k:{i:"aktif kontinu ###",e:"continuous active ###",z:"连续自动 ###"}},
   {n:"6",p:{i:"Partikulat debu < 100 µm (TSP)",e:"Particulate matter < 100 µm (TSP)",z:"总悬浮颗粒物 < 100 µm (TSP)"},u:"24 jam|24 hours|24 小时",v:["230 µg/m³"],k:{i:"aktif manual",e:"manual active",z:"手工"}},
   {n:"",p:{i:"Partikulat debu < 10 µm (PM₁₀)",e:"Particulate matter < 10 µm (PM₁₀)",z:"可吸入颗粒物 (PM₁₀)"},u:"24 jam|24 hours|24 小时",v:["75 µg/m³"],k:{i:"aktif kontinu / aktif manual",e:"continuous active / manual active",z:"连续自动 / 手工"}},
   {n:"",p:{i:"Partikulat debu < 10 µm (PM₁₀)",e:"Particulate matter < 10 µm (PM₁₀)",z:"可吸入颗粒物 (PM₁₀)"},u:"1 tahun|1 year|1 年",v:["40 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"",p:{i:"Partikulat debu < 2,5 µm (PM₂,₅)",e:"Particulate matter < 2.5 µm (PM₂.₅)",z:"细颗粒物 (PM₂.₅)"},u:"24 jam|24 hours|24 小时",v:["55 µg/m³"],k:{i:"aktif kontinu / aktif manual",e:"continuous active / manual active",z:"连续自动 / 手工"}},
   {n:"",p:{i:"Partikulat debu < 2,5 µm (PM₂,₅)",e:"Particulate matter < 2.5 µm (PM₂.₅)",z:"细颗粒物 (PM₂.₅)"},u:"1 tahun|1 year|1 年",v:["15 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"7",p:{i:"Timbal (Pb)",e:"Lead (Pb)",z:"铅 (Pb)"},u:"24 jam|24 hours|24 小时",v:["2 µg/m³"],k:{i:"aktif manual",e:"manual active",z:"手工"}}
  ],
  foot:{
   i:["µg/m³ = konsentrasi dalam mikrogram per meter kubik, pada kondisi atmosfer normal, yaitu tekanan (P) 1 atm dan temperatur (T) 25 °C.",
      "# Konsentrasi yang dilaporkan untuk waktu pengukuran 1 (satu) jam adalah hasil pengukuran setiap 30 (tiga puluh) menit — 2 kali pengukuran dalam 1 jam — dan dilakukan di antara pukul 11:00–14:00 waktu setempat.",
      "## Konsentrasi yang dilaporkan untuk waktu pengukuran 8 (delapan) jam adalah konsentrasi dari pengukuran yang dilakukan di antara pukul 06:00–18:00 waktu setempat.",
      "### Konsentrasi yang dilaporkan untuk waktu pengukuran 3 (tiga) jam adalah konsentrasi dari pengukuran yang dilakukan di antara pukul 06:00–10:00 waktu setempat."],
   e:["µg/m³ = concentration in micrograms per cubic metre at normal atmospheric conditions, i.e. pressure (P) 1 atm and temperature (T) 25 °C.",
      "# The concentration reported for a 1-hour averaging time is measured every 30 minutes — 2 measurements within the hour — taken between 11:00 and 14:00 local time.",
      "## The concentration reported for an 8-hour averaging time is derived from measurements taken between 06:00 and 18:00 local time.",
      "### The concentration reported for a 3-hour averaging time is derived from measurements taken between 06:00 and 10:00 local time."],
   z:["µg/m³ = 标准大气条件下（压力 P = 1 atm，温度 T = 25 °C）每立方米微克数的浓度。",
      "# 1 小时时段所报浓度为每 30 分钟测量一次（1 小时内测 2 次）的结果，且须在当地时间 11:00–14:00 之间进行。",
      "## 8 小时时段所报浓度取自当地时间 06:00–18:00 之间进行的测量。",
      "### 3 小时时段所报浓度取自当地时间 06:00–10:00 之间进行的测量。"]
  }
},

sea:{
  code:"PP 22/2021 Lampiran VIII",
  title:{i:"Baku Mutu Air Laut",e:"Sea Water Quality Standard",z:"海水水质标准"},
  cols:{i:["No","Parameter","Satuan","Pelabuhan","Wisata Bahari","Biota Laut"],
        e:["No","Parameter","Unit","Port","Marine Tourism","Marine Biota"],
        z:["序号","参数","单位","港口","海洋旅游","海洋生物"]},
  rows:[
   {n:"1",p:{i:"Warna",e:"Colour",z:"色度"},u:"Pt-Co",v:["—","30","—"],k:{i:"",e:"",z:""}},
   {n:"2",p:{i:"Kecerahan",e:"Water clarity",z:"水体清澈度"},u:"m",v:[">3",">6","coral: >5 · mangrove: — · lamun: >3"],k:{i:"",e:"",z:""}},
   {n:"3",p:{i:"Kekeruhan",e:"Turbidity",z:"浊度"},u:"NTU",v:["—","5","5"],k:{i:"",e:"",z:""}},
   {n:"4",p:{i:"Kebauan",e:"Odour",z:"嗅"},u:"—",v:["tidak berbau","tidak berbau","alami"],k:{i:"",e:"",z:""}},
   {n:"5",p:{i:"Padatan tersuspensi total",e:"Total Suspended Solids",z:"总悬浮物"},u:"mg/L",v:["80","20","coral: 20 · mangrove: 80 · lamun: 20"],k:{i:"",e:"",z:""}},
   {n:"6",p:{i:"Sampah",e:"Refuse / Litter",z:"垃圾"},u:"—",v:["nihil","nihil","nihil"],k:{i:"",e:"",z:""}},
   {n:"7",p:{i:"Suhu",e:"Temperature",z:"水温"},u:"°C",v:["alami","alami","alami · coral: 28-30 · mangrove: 28-32 · lamun: 28-30"],k:{i:"",e:"",z:""}},
   {n:"8",p:{i:"Lapisan minyak",e:"Oil film",z:"浮油"},u:"—",v:["nihil","nihil","nihil"],k:{i:"",e:"",z:""}},
   {n:"9",p:{i:"pH",e:"pH",z:"pH 值"},u:"—",v:["6,5 – 8,5","7 – 8,5","7 – 8,5"],k:{i:"",e:"",z:""}},
   {n:"10",p:{i:"Salinitas",e:"Salinity",z:"盐度"},u:"‰",v:["alami","alami","alami · coral: 33-34 · mangrove: s/d 34 · lamun: 33-34"],k:{i:"",e:"",z:""}},
   {n:"11",p:{i:"Oksigen terlarut (DO)",e:"Dissolved Oxygen (DO)",z:"溶解氧 (DO)"},u:"mg/L",v:["—",">5",">5"],k:{i:"",e:"",z:""}},
   {n:"12",p:{i:"BOD₅",e:"BOD₅",z:"五日生化需氧量 (BOD₅)"},u:"mg/L",v:["—","10","20"],k:{i:"",e:"",z:""}},
   {n:"13",p:{i:"Amonia total (NH₃-N)",e:"Total Ammonia (NH₃-N)",z:"总氨氮 (NH₃-N)"},u:"mg/L",v:["0,3","0,02","0,3"],k:{i:"",e:"",z:""}},
   {n:"14",p:{i:"Ortofosfat (PO₄-P)",e:"Orthophosphate (PO₄-P)",z:"正磷酸盐 (PO₄-P)"},u:"mg/L",v:["—","0,015","0,015"],k:{i:"",e:"",z:""}},
   {n:"15",p:{i:"Nitrat (NO₃-N)",e:"Nitrate (NO₃-N)",z:"硝酸盐 (NO₃-N)"},u:"mg/L",v:["—","0,06","0,06"],k:{i:"",e:"",z:""}},
   {n:"16",p:{i:"Sianida (CN⁻)",e:"Cyanide (CN⁻)",z:"氰化物 (CN⁻)"},u:"mg/L",v:["—","—","0,5"],k:{i:"",e:"",z:""}},
   {n:"17",p:{i:"Sulfida (H₂S)",e:"Sulphide (H₂S)",z:"硫化物 (H₂S)"},u:"mg/L",v:["0,03","0,002","0,01"],k:{i:"",e:"",z:""}},
   {n:"18",p:{i:"Hidrokarbon Petroleum Total (TPH)",e:"Total Petroleum Hydrocarbons (TPH)",z:"石油烃总量 (TPH)"},u:"mg/L",v:["1","—","0,02"],k:{i:"",e:"",z:""}},
   {n:"19",p:{i:"Senyawa Fenol total",e:"Total Phenolic Compounds",z:"总酚"},u:"mg/L",v:["0,002","0,001","0,002"],k:{i:"",e:"",z:""}},
   {n:"20",p:{i:"PAH (Poliaromatik hidrokarbon)",e:"PAH (Polyaromatic Hydrocarbons)",z:"多环芳烃 (PAH)"},u:"mg/L",v:["—","0,003","0,003"],k:{i:"",e:"",z:""}},
   {n:"21",p:{i:"PCB (poliklor bifenil)",e:"PCB (Polychlorinated Biphenyls)",z:"多氯联苯 (PCB)"},u:"µg/L",v:["0,01","0,005","0,01"],k:{i:"",e:"",z:""}},
   {n:"22",p:{i:"Surfaktan (deterjen) sebagai MBAS",e:"Surfactant (detergent) as MBAS",z:"表面活性剂（以 MBAS 计）"},u:"mg/L",v:["1","0,001","1"],k:{i:"",e:"",z:""}},
   {n:"23",p:{i:"Minyak dan Lemak",e:"Oil and Grease",z:"石油类与油脂"},u:"mg/L",v:["5","1","1"],k:{i:"",e:"",z:""}},
   {n:"24a",p:{i:"Pestisida — BHC",e:"Pesticide — BHC",z:"农药 — 六六六 (BHC)"},u:"µg/L",v:["—","210","210"],k:{i:"",e:"",z:""}},
   {n:"24b",p:{i:"Pestisida — Aldrin/Dieldrin",e:"Pesticide — Aldrin/Dieldrin",z:"农药 — 艾氏剂/狄氏剂"},u:"µg/L",v:["—","17","—"],k:{i:"",e:"",z:""}},
   {n:"24c",p:{i:"Pestisida — Chlordane",e:"Pesticide — Chlordane",z:"农药 — 氯丹"},u:"µg/L",v:["—","3","—"],k:{i:"",e:"",z:""}},
   {n:"24d",p:{i:"Pestisida — DDT",e:"Pesticide — DDT",z:"农药 — 滴滴涕 (DDT)"},u:"µg/L",v:["—","2","2"],k:{i:"",e:"",z:""}},
   {n:"24e",p:{i:"Pestisida — Heptachlor",e:"Pesticide — Heptachlor",z:"农药 — 七氯"},u:"µg/L",v:["—","18","—"],k:{i:"",e:"",z:""}},
   {n:"24f",p:{i:"Pestisida — Lindane",e:"Pesticide — Lindane",z:"农药 — 林丹"},u:"µg/L",v:["—","56","—"],k:{i:"",e:"",z:""}},
   {n:"24g",p:{i:"Pestisida — Methoxychlor",e:"Pesticide — Methoxychlor",z:"农药 — 甲氧滴滴涕"},u:"µg/L",v:["—","35","—"],k:{i:"",e:"",z:""}},
   {n:"24h",p:{i:"Pestisida — Endrin",e:"Pesticide — Endrin",z:"农药 — 异狄氏剂"},u:"µg/L",v:["—","1","4"],k:{i:"",e:"",z:""}},
   {n:"24i",p:{i:"Pestisida — Toxaphan",e:"Pesticide — Toxaphene",z:"农药 — 毒杀芬"},u:"µg/L",v:["—","5","—"],k:{i:"",e:"",z:""}},
   {n:"25",p:{i:"TBT (tri butil tin)",e:"TBT (Tributyltin)",z:"三丁基锡 (TBT)"},u:"µg/L",v:["0,01","—","0,01"],k:{i:"",e:"",z:""}},
   {n:"26",p:{i:"Raksa (Hg)",e:"Mercury (Hg)",z:"汞 (Hg)"},u:"mg/L",v:["0,003","0,002","0,001"],k:{i:"",e:"",z:""}},
   {n:"27",p:{i:"Kromium heksavalen (Cr(VI))",e:"Hexavalent Chromium (Cr(VI))",z:"六价铬 (Cr(VI))"},u:"mg/L",v:["—","0,002","0,005"],k:{i:"",e:"",z:""}},
   {n:"28",p:{i:"Arsen (As)",e:"Arsenic (As)",z:"砷 (As)"},u:"mg/L",v:["—","0,025","0,012"],k:{i:"",e:"",z:""}},
   {n:"29",p:{i:"Kadmium (Cd)",e:"Cadmium (Cd)",z:"镉 (Cd)"},u:"mg/L",v:["0,01","0,002","0,001"],k:{i:"",e:"",z:""}},
   {n:"30",p:{i:"Tembaga (Cu)",e:"Copper (Cu)",z:"铜 (Cu)"},u:"mg/L",v:["0,05","0,05","0,008"],k:{i:"",e:"",z:""}},
   {n:"31",p:{i:"Timbal (Pb)",e:"Lead (Pb)",z:"铅 (Pb)"},u:"mg/L",v:["0,05","0,005","0,008"],k:{i:"",e:"",z:""}},
   {n:"32",p:{i:"Seng (Zn)",e:"Zinc (Zn)",z:"锌 (Zn)"},u:"mg/L",v:["0,1","0,095","0,05"],k:{i:"",e:"",z:""}},
   {n:"33",p:{i:"Nikel (Ni)",e:"Nickel (Ni)",z:"镍 (Ni)"},u:"mg/L",v:["—","0,075","0,05"],k:{i:"",e:"",z:""}},
   {n:"34",p:{i:"Fecal coliform",e:"Faecal coliform",z:"粪大肠菌群"},u:"Jml/100 mL",v:["—","200","—"],k:{i:"",e:"",z:""}},
   {n:"35",p:{i:"Coliform (total)",e:"Coliform (total)",z:"总大肠菌群"},u:"Jml/100 mL",v:["1000","1000","1000"],k:{i:"",e:"",z:""}},
   {n:"36",p:{i:"Patogen",e:"Pathogens",z:"病原体"},u:"sel/100 mL",v:["—","nihil","nihil"],k:{i:"",e:"",z:""}},
   {n:"37",p:{i:"Fitoplankton",e:"Phytoplankton",z:"浮游植物"},u:"sel/mL",v:["—","1000","1000"],k:{i:"",e:"",z:""}},
   {n:"38",p:{i:"Radioaktifitas",e:"Radioactivity",z:"放射性"},u:"Bq/L",v:["—","4","4"],k:{i:"",e:"",z:""}}
  ],
  foot:{
   i:["\"Alami\" adalah kondisi normal suatu lingkungan yang bervariasi setiap saat (siang/malam) sesuai keadaan alaminya, dipakai sebagai acuan.",
      "coral / mangrove / lamun = nilai khusus untuk peruntukan terumbu karang, hutan bakau, dan padang lamun.",
      "Nilai \"nihil\" berarti tidak boleh terdeteksi; \"s/d\" berarti sampai dengan.",
      "Catatan lengkap mengenai fitoplankton dan Harmful Algae Bloom (HAB) tercantum pada keterangan Lampiran VIII — teks aslinya sebagian tidak terbaca pada salinan PDF; rujuk dokumen resmi untuk kutipan verbatim."],
   e:["\"Alami\" (natural) means the normal condition of an environment which varies naturally through the day and night; it is used as the reference.",
      "coral / mangrove / lamun = specific values for coral reef, mangrove and seagrass designations respectively.",
      "\"nihil\" means it must not be detectable; \"s/d\" means \"up to\".",
      "The full note on phytoplankton and Harmful Algae Bloom (HAB) appears in the Lampiran VIII remarks — parts of the original are illegible in the PDF copy; consult the official document for a verbatim citation."],
   z:["\"Alami\"（天然）指环境的正常状态，随昼夜自然变化，以此作为基准。",
      "coral / mangrove / lamun = 分别对应珊瑚礁、红树林与海草床用途的专用限值。",
      "\"nihil\" 表示不得检出；\"s/d\" 表示\"至\"。",
      "关于浮游植物与有害藻华（HAB）的完整说明见附件 VIII 备注 — PDF 副本中该段原文部分不可辨识，逐字引用请查阅官方文件。"]
  }
}

};
