// ================================================================
// PP 22/2021 — Baku Mutu Lingkungan (Environmental Quality Standards)
// Lampiran VI  : Baku Mutu Air Nasional (I. Sungai · II. Danau)
// Lampiran VII : Baku Mutu Udara Ambien
// Lampiran VIII: Baku Mutu Air Laut
// Values transcribed from the official PDF (pdftotext -table mode) and
// cross-checked parameter-by-parameter against the regulation text.
// Labels carried in 3 languages: i = Bahasa Indonesia (authoritative
// legal term) / e = English / z = 简体中文.
// Every table is exportable to Excel via exportEnvTable().
// ================================================================
window.ENV_TABLES = {

river:{
  code:"PP 22/2021 Lampiran VI-I",
  title:{i:"Baku Mutu Air Sungai dan Sejenisnya",e:"River Water Quality Standard",z:"河流及类似水体水质标准"},
  cols:{i:["No","Parameter","Satuan","Kelas I","Kelas II","Kelas III","Kelas IV","Keterangan"],
        e:["No","Parameter","Unit","Class I","Class II","Class III","Class IV","Remarks"],
        z:["序号","参数","单位","I 类","II 类","III 类","IV 类","备注"]},
  rows:[
   {n:"1",p:{i:"Temperatur",e:"Temperature",z:"水温"},u:"°C",v:["Dev 3","Dev 3","Dev 3","Dev 3"],k:{i:"Perbedaan dengan suhu udara di atas permukaan air",e:"Deviation from air temperature above the water surface",z:"与水面上方气温的偏差"}},
   {n:"2",p:{i:"Padatan terlarut total (TDS)",e:"Total Dissolved Solids (TDS)",z:"总溶解固体 (TDS)"},u:"mg/L",v:["1.000","1.000","1.000","2.000"],k:{i:"Tidak berlaku untuk muara",e:"Not applicable to estuaries",z:"不适用于河口"}},
   {n:"3",p:{i:"Padatan tersuspensi total (TSS)",e:"Total Suspended Solids (TSS)",z:"总悬浮物 (TSS)"},u:"mg/L",v:["40","50","100","400"],k:{i:"",e:"",z:""}},
   {n:"4",p:{i:"Warna",e:"Colour",z:"色度"},u:"Pt-Co Unit",v:["15","50","100","—"],k:{i:"Tidak berlaku untuk air gambut (berdasarkan kondisi alaminya)",e:"Not applicable to peat water (based on its natural condition)",z:"不适用于泥炭水（按其天然状态）"}},
   {n:"5",p:{i:"Derajat keasaman (pH)",e:"Acidity (pH)",z:"pH 值"},u:"—",v:["6-9","6-9","6-9","6-9"],k:{i:"Tidak berlaku untuk air gambut (berdasarkan kondisi alaminya)",e:"Not applicable to peat water (based on its natural condition)",z:"不适用于泥炭水（按其天然状态）"}},
   {n:"6",p:{i:"Kebutuhan oksigen biokimiawi (BOD)",e:"Biochemical Oxygen Demand (BOD)",z:"生化需氧量 (BOD)"},u:"mg/L",v:["2","3","6","12"],k:{i:"",e:"",z:""}},
   {n:"7",p:{i:"Kebutuhan oksigen kimiawi (COD)",e:"Chemical Oxygen Demand (COD)",z:"化学需氧量 (COD)"},u:"mg/L",v:["10","25","40","80"],k:{i:"",e:"",z:""}},
   {n:"8",p:{i:"Oksigen terlarut (DO)",e:"Dissolved Oxygen (DO)",z:"溶解氧 (DO)"},u:"mg/L",v:["6","4","3","1"],k:{i:"Batas minimal",e:"Minimum limit",z:"最低限值"}},
   {n:"9",p:{i:"Sulfat (SO₄²⁻)",e:"Sulphate (SO₄²⁻)",z:"硫酸盐 (SO₄²⁻)"},u:"mg/L",v:["300","300","300","400"],k:{i:"",e:"",z:""}},
   {n:"10",p:{i:"Klorida (Cl⁻)",e:"Chloride (Cl⁻)",z:"氯化物 (Cl⁻)"},u:"mg/L",v:["300","300","300","600"],k:{i:"",e:"",z:""}},
   {n:"11",p:{i:"Nitrat (sebagai N)",e:"Nitrate (as N)",z:"硝酸盐（以 N 计）"},u:"mg/L",v:["10","10","20","20"],k:{i:"",e:"",z:""}},
   {n:"12",p:{i:"Nitrit (sebagai N)",e:"Nitrite (as N)",z:"亚硝酸盐（以 N 计）"},u:"mg/L",v:["0,06","0,06","0,06","—"],k:{i:"Bagi air baku air minum tidak dipersyaratkan",e:"Not required where used as drinking-water raw water",z:"作为饮用水源水时不作要求"}},
   {n:"13",p:{i:"Amoniak (sebagai N)",e:"Ammonia (as N)",z:"氨氮（以 N 计）"},u:"mg/L",v:["0,1","0,2","0,5","—"],k:{i:"",e:"",z:""}},
   {n:"14",p:{i:"Total Nitrogen",e:"Total Nitrogen",z:"总氮"},u:"mg/L",v:["15","15","25","—"],k:{i:"",e:"",z:""}},
   {n:"15",p:{i:"Total Fosfat (sebagai P)",e:"Total Phosphate (as P)",z:"总磷（以 P 计）"},u:"mg/L",v:["0,2","0,2","1","—"],k:{i:"",e:"",z:""}},
   {n:"16",p:{i:"Fluorida (F⁻)",e:"Fluoride (F⁻)",z:"氟化物 (F⁻)"},u:"mg/L",v:["1","1,5","1,5","—"],k:{i:"",e:"",z:""}},
   {n:"17",p:{i:"Belerang sebagai H₂S",e:"Sulphide as H₂S",z:"硫化物（以 H₂S 计）"},u:"mg/L",v:["0,002","0,002","0,002","—"],k:{i:"",e:"",z:""}},
   {n:"18",p:{i:"Sianida (CN⁻)",e:"Cyanide (CN⁻)",z:"氰化物 (CN⁻)"},u:"mg/L",v:["0,02","0,02","0,02","—"],k:{i:"",e:"",z:""}},
   {n:"19",p:{i:"Klorin bebas",e:"Free Chlorine",z:"游离氯"},u:"mg/L",v:["0,03","0,03","0,03","—"],k:{i:"Bagi air baku air minum tidak dipersyaratkan",e:"Not required where used as drinking-water raw water",z:"作为饮用水源水时不作要求"}},
   {n:"20",p:{i:"Barium (Ba) terlarut",e:"Dissolved Barium (Ba)",z:"溶解性钡 (Ba)"},u:"mg/L",v:["1,0","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"21",p:{i:"Boron (B) terlarut",e:"Dissolved Boron (B)",z:"溶解性硼 (B)"},u:"mg/L",v:["1,0","1,0","1,0","1,0"],k:{i:"",e:"",z:""}},
   {n:"22",p:{i:"Merkuri (Hg) terlarut",e:"Dissolved Mercury (Hg)",z:"溶解性汞 (Hg)"},u:"mg/L",v:["0,001","0,002","0,002","0,005"],k:{i:"",e:"",z:""}},
   {n:"23",p:{i:"Arsen (As) terlarut",e:"Dissolved Arsenic (As)",z:"溶解性砷 (As)"},u:"mg/L",v:["0,05","0,05","0,05","0,10"],k:{i:"",e:"",z:""}},
   {n:"24",p:{i:"Selenium (Se) terlarut",e:"Dissolved Selenium (Se)",z:"溶解性硒 (Se)"},u:"mg/L",v:["0,01","0,05","0,05","0,05"],k:{i:"",e:"",z:""}},
   {n:"25",p:{i:"Besi (Fe) terlarut",e:"Dissolved Iron (Fe)",z:"溶解性铁 (Fe)"},u:"mg/L",v:["0,3","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"26",p:{i:"Kadmium (Cd) terlarut",e:"Dissolved Cadmium (Cd)",z:"溶解性镉 (Cd)"},u:"mg/L",v:["0,01","0,01","0,01","0,01"],k:{i:"",e:"",z:""}},
   {n:"27",p:{i:"Kobalt (Co) terlarut",e:"Dissolved Cobalt (Co)",z:"溶解性钴 (Co)"},u:"mg/L",v:["0,2","0,2","0,2","0,2"],k:{i:"",e:"",z:""}},
   {n:"28",p:{i:"Mangan (Mn) terlarut",e:"Dissolved Manganese (Mn)",z:"溶解性锰 (Mn)"},u:"mg/L",v:["0,1","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"29",p:{i:"Nikel (Ni) terlarut",e:"Dissolved Nickel (Ni)",z:"溶解性镍 (Ni)"},u:"mg/L",v:["0,05","0,05","0,05","0,1"],k:{i:"",e:"",z:""}},
   {n:"30",p:{i:"Seng (Zn) terlarut",e:"Dissolved Zinc (Zn)",z:"溶解性锌 (Zn)"},u:"mg/L",v:["0,05","0,05","0,05","2"],k:{i:"",e:"",z:""}},
   {n:"31",p:{i:"Tembaga (Cu) terlarut",e:"Dissolved Copper (Cu)",z:"溶解性铜 (Cu)"},u:"mg/L",v:["0,02","0,02","0,02","0,2"],k:{i:"",e:"",z:""}},
   {n:"32",p:{i:"Timbal (Pb) terlarut",e:"Dissolved Lead (Pb)",z:"溶解性铅 (Pb)"},u:"mg/L",v:["0,03","0,03","0,03","0,5"],k:{i:"",e:"",z:""}},
   {n:"33",p:{i:"Kromium heksavalen (Cr(VI))",e:"Hexavalent Chromium (Cr(VI))",z:"六价铬 (Cr(VI))"},u:"mg/L",v:["0,05","0,05","0,05","1"],k:{i:"",e:"",z:""}},
   {n:"34",p:{i:"Minyak dan lemak",e:"Oil and Grease",z:"石油类与油脂"},u:"mg/L",v:["1","1","1","10"],k:{i:"",e:"",z:""}},
   {n:"35",p:{i:"Deterjen total",e:"Total Detergent (MBAS)",z:"总洗涤剂 (MBAS)"},u:"mg/L",v:["0,2","0,2","0,2","—"],k:{i:"",e:"",z:""}},
   {n:"36",p:{i:"Fenol",e:"Phenol",z:"酚类"},u:"mg/L",v:["0,002","0,005","0,01","0,02"],k:{i:"",e:"",z:""}},
   {n:"37",p:{i:"Aldrin/Dieldrin",e:"Aldrin/Dieldrin",z:"艾氏剂/狄氏剂"},u:"µg/L",v:["17","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"38",p:{i:"BHC",e:"BHC",z:"六六六 (BHC)"},u:"µg/L",v:["210","210","210","—"],k:{i:"",e:"",z:""}},
   {n:"39",p:{i:"Chlordane",e:"Chlordane",z:"氯丹"},u:"µg/L",v:["3","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"40",p:{i:"DDT",e:"DDT",z:"滴滴涕 (DDT)"},u:"µg/L",v:["2","2","2","2"],k:{i:"",e:"",z:""}},
   {n:"41",p:{i:"Endrin",e:"Endrin",z:"异狄氏剂"},u:"µg/L",v:["1","4","4","—"],k:{i:"",e:"",z:""}},
   {n:"42",p:{i:"Heptachlor",e:"Heptachlor",z:"七氯"},u:"µg/L",v:["18","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"43",p:{i:"Lindane",e:"Lindane",z:"林丹"},u:"µg/L",v:["56","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"44",p:{i:"Methoxychlor",e:"Methoxychlor",z:"甲氧滴滴涕"},u:"µg/L",v:["35","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"45",p:{i:"Toxaphan",e:"Toxaphene",z:"毒杀芬"},u:"µg/L",v:["5","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"46",p:{i:"Fecal Coliform",e:"Faecal Coliform",z:"粪大肠菌群"},u:"MPN/100 mL",v:["100","1.000","2.000","2.000"],k:{i:"",e:"",z:""}},
   {n:"47",p:{i:"Total Coliform",e:"Total Coliform",z:"总大肠菌群"},u:"MPN/100 mL",v:["1.000","5.000","10.000","10.000"],k:{i:"",e:"",z:""}},
   {n:"48",p:{i:"Sampah",e:"Refuse / Litter",z:"垃圾"},u:"—",v:["nihil","nihil","nihil","nihil"],k:{i:"nihil = tidak ada",e:"nihil = none",z:"nihil = 无"}},
   {n:"49",p:{i:"Radioaktivitas — Gross-A",e:"Radioactivity — Gross-α",z:"放射性 — 总 α"},u:"Bq/L",v:["0,1","0,1","0,1","0,1"],k:{i:"",e:"",z:""}},
   {n:"",p:{i:"Radioaktivitas — Gross-B",e:"Radioactivity — Gross-β",z:"放射性 — 总 β"},u:"Bq/L",v:["1","1","1","1"],k:{i:"",e:"",z:""}}
  ]
},

lake:{
  code:"PP 22/2021 Lampiran VI-II",
  title:{i:"Baku Mutu Air Danau dan Sejenisnya",e:"Lake Water Quality Standard",z:"湖泊及类似水体水质标准"},
  cols:{i:["No","Parameter","Satuan","Kelas I","Kelas II","Kelas III","Kelas IV","Keterangan"],
        e:["No","Parameter","Unit","Class I","Class II","Class III","Class IV","Remarks"],
        z:["序号","参数","单位","I 类","II 类","III 类","IV 类","备注"]},
  rows:[
   {n:"1",p:{i:"Temperatur",e:"Temperature",z:"水温"},u:"°C",v:["Dev 3","Dev 3","Dev 3","Dev 3"],k:{i:"Perbedaan dengan suhu udara di atas permukaan air",e:"Deviation from air temperature above the water surface",z:"与水面上方气温的偏差"}},
   {n:"2",p:{i:"Padatan terlarut total (TDS)",e:"Total Dissolved Solids (TDS)",z:"总溶解固体 (TDS)"},u:"mg/L",v:["1.000","1.000","1.000","1.000"],k:{i:"",e:"",z:""}},
   {n:"3",p:{i:"Padatan tersuspensi total (TSS)",e:"Total Suspended Solids (TSS)",z:"总悬浮物 (TSS)"},u:"mg/L",v:["25","50","100","400"],k:{i:"",e:"",z:""}},
   {n:"4",p:{i:"Transparansi",e:"Transparency",z:"透明度"},u:"m",v:["10","4","2,5","—"],k:{i:"",e:"",z:""}},
   {n:"5",p:{i:"Warna",e:"Colour",z:"色度"},u:"Pt-Co Unit",v:["15","50","100","—"],k:{i:"",e:"",z:""}},
   {n:"6",p:{i:"Derajat keasaman (pH)",e:"Acidity (pH)",z:"pH 值"},u:"—",v:["6-9","6-9","6-9","6-9"],k:{i:"Tidak berlaku untuk air gambut (berdasarkan kondisi alaminya)",e:"Not applicable to peat water (based on its natural condition)",z:"不适用于泥炭水（按其天然状态）"}},
   {n:"7",p:{i:"Kebutuhan oksigen biokimiawi (BOD)",e:"Biochemical Oxygen Demand (BOD)",z:"生化需氧量 (BOD)"},u:"mg/L",v:["2","3","6","12"],k:{i:"",e:"",z:""}},
   {n:"8",p:{i:"Kebutuhan oksigen kimiawi (COD)",e:"Chemical Oxygen Demand (COD)",z:"化学需氧量 (COD)"},u:"mg/L",v:["10","25","40","80"],k:{i:"",e:"",z:""}},
   {n:"9",p:{i:"Oksigen terlarut (DO)",e:"Dissolved Oxygen (DO)",z:"溶解氧 (DO)"},u:"mg/L",v:["6","4","3","1"],k:{i:"Batas minimal",e:"Minimum limit",z:"最低限值"}},
   {n:"10",p:{i:"Sulfat (SO₄²⁻)",e:"Sulphate (SO₄²⁻)",z:"硫酸盐 (SO₄²⁻)"},u:"mg/L",v:["300","300","300","400"],k:{i:"",e:"",z:""}},
   {n:"11",p:{i:"Klorida (Cl⁻)",e:"Chloride (Cl⁻)",z:"氯化物 (Cl⁻)"},u:"mg/L",v:["300","300","300","600"],k:{i:"",e:"",z:""}},
   {n:"12",p:{i:"Total Nitrogen",e:"Total Nitrogen",z:"总氮"},u:"mg/L",v:["0,65","0,75","1,90","—"],k:{i:"",e:"",z:""}},
   {n:"13",p:{i:"Total Fosfat (sebagai P)",e:"Total Phosphate (as P)",z:"总磷（以 P 计）"},u:"mg/L",v:["0,01","0,03","0,1","—"],k:{i:"",e:"",z:""}},
   {n:"14",p:{i:"Fluorida (F⁻)",e:"Fluoride (F⁻)",z:"氟化物 (F⁻)"},u:"mg/L",v:["1","1,5","1,5","—"],k:{i:"",e:"",z:""}},
   {n:"15",p:{i:"Belerang sebagai H₂S",e:"Sulphide as H₂S",z:"硫化物（以 H₂S 计）"},u:"mg/L",v:["0,002","0,002","0,002","—"],k:{i:"",e:"",z:""}},
   {n:"16",p:{i:"Sianida (CN⁻)",e:"Cyanide (CN⁻)",z:"氰化物 (CN⁻)"},u:"mg/L",v:["0,02","0,02","0,02","—"],k:{i:"",e:"",z:""}},
   {n:"17",p:{i:"Klorin bebas",e:"Free Chlorine",z:"游离氯"},u:"mg/L",v:["0,03","0,03","0,03","—"],k:{i:"Bagi air baku air minum tidak dipersyaratkan",e:"Not required where used as drinking-water raw water",z:"作为饮用水源水时不作要求"}},
   {n:"18",p:{i:"Barium (Ba) terlarut",e:"Dissolved Barium (Ba)",z:"溶解性钡 (Ba)"},u:"mg/L",v:["1,0","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"19",p:{i:"Boron (B) terlarut",e:"Dissolved Boron (B)",z:"溶解性硼 (B)"},u:"mg/L",v:["1,0","1,0","1,0","1,0"],k:{i:"",e:"",z:""}},
   {n:"20",p:{i:"Merkuri (Hg) terlarut",e:"Dissolved Mercury (Hg)",z:"溶解性汞 (Hg)"},u:"mg/L",v:["0,001","0,002","0,002","0,005"],k:{i:"",e:"",z:""}},
   {n:"21",p:{i:"Arsen (As) terlarut",e:"Dissolved Arsenic (As)",z:"溶解性砷 (As)"},u:"mg/L",v:["0,05","0,05","0,05","0,1"],k:{i:"",e:"",z:""}},
   {n:"22",p:{i:"Selenium (Se) terlarut",e:"Dissolved Selenium (Se)",z:"溶解性硒 (Se)"},u:"mg/L",v:["0,01","0,05","0,05","0,05"],k:{i:"",e:"",z:""}},
   {n:"23",p:{i:"Besi (Fe) terlarut",e:"Dissolved Iron (Fe)",z:"溶解性铁 (Fe)"},u:"mg/L",v:["0,3","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"24",p:{i:"Kadmium (Cd) terlarut",e:"Dissolved Cadmium (Cd)",z:"溶解性镉 (Cd)"},u:"mg/L",v:["0,01","0,01","0,01","0,01"],k:{i:"",e:"",z:""}},
   {n:"25",p:{i:"Kobalt (Co) terlarut",e:"Dissolved Cobalt (Co)",z:"溶解性钴 (Co)"},u:"mg/L",v:["0,2","0,2","0,2","0,2"],k:{i:"",e:"",z:""}},
   {n:"26",p:{i:"Mangan (Mn) terlarut",e:"Dissolved Manganese (Mn)",z:"溶解性锰 (Mn)"},u:"mg/L",v:["0,4","0,4","0,5","1,0"],k:{i:"",e:"",z:""}},
   {n:"27",p:{i:"Nikel (Ni) terlarut",e:"Dissolved Nickel (Ni)",z:"溶解性镍 (Ni)"},u:"mg/L",v:["0,05","0,05","0,05","0,1"],k:{i:"",e:"",z:""}},
   {n:"28",p:{i:"Seng (Zn) terlarut",e:"Dissolved Zinc (Zn)",z:"溶解性锌 (Zn)"},u:"mg/L",v:["0,05","0,05","0,05","2,0"],k:{i:"",e:"",z:""}},
   {n:"29",p:{i:"Tembaga (Cu) terlarut",e:"Dissolved Copper (Cu)",z:"溶解性铜 (Cu)"},u:"mg/L",v:["0,02","0,02","0,02","0,2"],k:{i:"",e:"",z:""}},
   {n:"30",p:{i:"Timbal (Pb) terlarut",e:"Dissolved Lead (Pb)",z:"溶解性铅 (Pb)"},u:"mg/L",v:["0,03","0,03","0,03","0,5"],k:{i:"",e:"",z:""}},
   {n:"31",p:{i:"Kromium heksavalen (Cr(VI))",e:"Hexavalent Chromium (Cr(VI))",z:"六价铬 (Cr(VI))"},u:"mg/L",v:["0,05","0,05","0,05","1"],k:{i:"",e:"",z:""}},
   {n:"32",p:{i:"Minyak dan lemak",e:"Oil and Grease",z:"石油类与油脂"},u:"mg/L",v:["1","1","1","10"],k:{i:"",e:"",z:""}},
   {n:"33",p:{i:"Deterjen total",e:"Total Detergent (MBAS)",z:"总洗涤剂 (MBAS)"},u:"mg/L",v:["0,2","0,2","0,2","—"],k:{i:"",e:"",z:""}},
   {n:"34",p:{i:"Fenol",e:"Phenol",z:"酚类"},u:"mg/L",v:["0,002","0,005","0,01","0,02"],k:{i:"",e:"",z:""}},
   {n:"35",p:{i:"Aldrin/Dieldrin",e:"Aldrin/Dieldrin",z:"艾氏剂/狄氏剂"},u:"µg/L",v:["17","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"36",p:{i:"BHC",e:"BHC",z:"六六六 (BHC)"},u:"µg/L",v:["210","210","210","—"],k:{i:"",e:"",z:""}},
   {n:"37",p:{i:"Chlordane",e:"Chlordane",z:"氯丹"},u:"µg/L",v:["3","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"38",p:{i:"DDT",e:"DDT",z:"滴滴涕 (DDT)"},u:"µg/L",v:["2","2","2","2"],k:{i:"",e:"",z:""}},
   {n:"39",p:{i:"Endrin",e:"Endrin",z:"异狄氏剂"},u:"µg/L",v:["1","4","4","—"],k:{i:"",e:"",z:""}},
   {n:"40",p:{i:"Heptachlor",e:"Heptachlor",z:"七氯"},u:"µg/L",v:["18","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"41",p:{i:"Lindane",e:"Lindane",z:"林丹"},u:"µg/L",v:["56","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"42",p:{i:"Methoxychlor",e:"Methoxychlor",z:"甲氧滴滴涕"},u:"µg/L",v:["35","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"43",p:{i:"Toxaphan",e:"Toxaphene",z:"毒杀芬"},u:"µg/L",v:["5","—","—","—"],k:{i:"",e:"",z:""}},
   {n:"44",p:{i:"Fecal Coliform",e:"Faecal Coliform",z:"粪大肠菌群"},u:"MPN/100 mL",v:["100","1.000","2.000","2.000"],k:{i:"",e:"",z:""}},
   {n:"45",p:{i:"Total Coliform",e:"Total Coliform",z:"总大肠菌群"},u:"MPN/100 mL",v:["1.000","5.000","10.000","10.000"],k:{i:"",e:"",z:""}},
   {n:"46",p:{i:"Klorofil-a",e:"Chlorophyll-a",z:"叶绿素 a"},u:"mg/m³",v:["10","50","100","200"],k:{i:"",e:"",z:""}},
   {n:"47",p:{i:"Sampah",e:"Refuse / Litter",z:"垃圾"},u:"—",v:["nihil","nihil","nihil","nihil"],k:{i:"nihil = tidak ada",e:"nihil = none",z:"nihil = 无"}},
   {n:"48",p:{i:"Radioaktivitas — Gross-A",e:"Radioactivity — Gross-α",z:"放射性 — 总 α"},u:"Bq/L",v:["0,1","0,1","0,1","0,1"],k:{i:"",e:"",z:""}},
   {n:"",p:{i:"Radioaktivitas — Gross-B",e:"Radioactivity — Gross-β",z:"放射性 — 总 β"},u:"Bq/L",v:["1","1","1","1"],k:{i:"",e:"",z:""}}
  ]
},

air:{
  code:"PP 22/2021 Lampiran VII",
  title:{i:"Baku Mutu Udara Ambien",e:"Ambient Air Quality Standard",z:"环境空气质量标准"},
  cols:{i:["No","Parameter","Waktu Pengukuran","Baku Mutu","Sistem Pengukuran"],
        e:["No","Parameter","Averaging Time","Limit Value","Measurement System"],
        z:["序号","参数","测量时段","标准限值","测量方式"]},
  rows:[
   {n:"1",p:{i:"Sulfur Dioksida (SO₂)",e:"Sulphur Dioxide (SO₂)",z:"二氧化硫 (SO₂)"},u:"1 jam|1 hour|1 小时",v:["150 µg/m³"],k:{i:"aktif kontinu / aktif manual",e:"continuous active / manual active",z:"连续自动 / 手工"}},
   {n:"",p:{i:"Sulfur Dioksida (SO₂)",e:"Sulphur Dioxide (SO₂)",z:"二氧化硫 (SO₂)"},u:"24 jam|24 hours|24 小时",v:["75 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"",p:{i:"Sulfur Dioksida (SO₂)",e:"Sulphur Dioxide (SO₂)",z:"二氧化硫 (SO₂)"},u:"1 tahun|1 year|1 年",v:["45 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"2",p:{i:"Karbon Monoksida (CO)",e:"Carbon Monoxide (CO)",z:"一氧化碳 (CO)"},u:"1 jam|1 hour|1 小时",v:["10.000 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"",p:{i:"Karbon Monoksida (CO)",e:"Carbon Monoxide (CO)",z:"一氧化碳 (CO)"},u:"8 jam|8 hours|8 小时",v:["4.000 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"3",p:{i:"Nitrogen Dioksida (NO₂)",e:"Nitrogen Dioxide (NO₂)",z:"二氧化氮 (NO₂)"},u:"1 jam|1 hour|1 小时",v:["200 µg/m³"],k:{i:"aktif kontinu / aktif manual",e:"continuous active / manual active",z:"连续自动 / 手工"}},
   {n:"",p:{i:"Nitrogen Dioksida (NO₂)",e:"Nitrogen Dioxide (NO₂)",z:"二氧化氮 (NO₂)"},u:"24 jam|24 hours|24 小时",v:["65 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"",p:{i:"Nitrogen Dioksida (NO₂)",e:"Nitrogen Dioxide (NO₂)",z:"二氧化氮 (NO₂)"},u:"1 tahun|1 year|1 年",v:["50 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"4",p:{i:"Oksidan fotokimia (Ox) sebagai Ozon (O₃)",e:"Photochemical Oxidants (Ox) as Ozone (O₃)",z:"光化学氧化剂（以臭氧 O₃ 计）"},u:"1 jam|1 hour|1 小时",v:["150 µg/m³"],k:{i:"aktif kontinu / aktif manual #",e:"continuous active / manual active #",z:"连续自动 / 手工 #"}},
   {n:"",p:{i:"Oksidan fotokimia (Ox) sebagai Ozon (O₃)",e:"Photochemical Oxidants (Ox) as Ozone (O₃)",z:"光化学氧化剂（以臭氧 O₃ 计）"},u:"8 jam|8 hours|8 小时",v:["100 µg/m³"],k:{i:"aktif kontinu ##",e:"continuous active ##",z:"连续自动 ##"}},
   {n:"",p:{i:"Oksidan fotokimia (Ox) sebagai Ozon (O₃)",e:"Photochemical Oxidants (Ox) as Ozone (O₃)",z:"光化学氧化剂（以臭氧 O₃ 计）"},u:"1 tahun|1 year|1 年",v:["35 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"5",p:{i:"Hidrokarbon Non Metana (NMHC)",e:"Non-Methane Hydrocarbons (NMHC)",z:"非甲烷总烃 (NMHC)"},u:"3 jam|3 hours|3 小时",v:["160 µg/m³"],k:{i:"aktif kontinu ###",e:"continuous active ###",z:"连续自动 ###"}},
   {n:"6",p:{i:"Partikulat debu < 100 µm (TSP)",e:"Particulate matter < 100 µm (TSP)",z:"总悬浮颗粒物 < 100 µm (TSP)"},u:"24 jam|24 hours|24 小时",v:["230 µg/m³"],k:{i:"aktif manual",e:"manual active",z:"手工"}},
   {n:"",p:{i:"Partikulat debu < 10 µm (PM₁₀)",e:"Particulate matter < 10 µm (PM₁₀)",z:"可吸入颗粒物 (PM₁₀)"},u:"24 jam|24 hours|24 小时",v:["75 µg/m³"],k:{i:"aktif kontinu / aktif manual",e:"continuous active / manual active",z:"连续自动 / 手工"}},
   {n:"",p:{i:"Partikulat debu < 10 µm (PM₁₀)",e:"Particulate matter < 10 µm (PM₁₀)",z:"可吸入颗粒物 (PM₁₀)"},u:"1 tahun|1 year|1 年",v:["40 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"",p:{i:"Partikulat debu < 2,5 µm (PM₂,₅)",e:"Particulate matter < 2.5 µm (PM₂.₅)",z:"细颗粒物 (PM₂.₅)"},u:"24 jam|24 hours|24 小时",v:["55 µg/m³"],k:{i:"aktif kontinu / aktif manual",e:"continuous active / manual active",z:"连续自动 / 手工"}},
   {n:"",p:{i:"Partikulat debu < 2,5 µm (PM₂,₅)",e:"Particulate matter < 2.5 µm (PM₂.₅)",z:"细颗粒物 (PM₂.₅)"},u:"1 tahun|1 year|1 年",v:["15 µg/m³"],k:{i:"aktif kontinu",e:"continuous active",z:"连续自动"}},
   {n:"7",p:{i:"Timbal (Pb)",e:"Lead (Pb)",z:"铅 (Pb)"},u:"24 jam|24 hours|24 小时",v:["2 µg/m³"],k:{i:"aktif manual",e:"manual active",z:"手工"}}
  ],
  foot:{
   i:["µg/m³ = konsentrasi dalam mikrogram per meter kubik, pada kondisi atmosfer normal, yaitu tekanan (P) 1 atm dan temperatur (T) 25 °C.",
      "# Konsentrasi yang dilaporkan untuk waktu pengukuran 1 (satu) jam adalah hasil pengukuran setiap 30 (tiga puluh) menit — 2 kali pengukuran dalam 1 jam — dan dilakukan di antara pukul 11:00–14:00 waktu setempat.",
      "## Konsentrasi yang dilaporkan untuk waktu pengukuran 8 (delapan) jam adalah konsentrasi dari pengukuran yang dilakukan di antara pukul 06:00–18:00 waktu setempat.",
      "### Konsentrasi yang dilaporkan untuk waktu pengukuran 3 (tiga) jam adalah konsentrasi dari pengukuran yang dilakukan di antara pukul 06:00–10:00 waktu setempat."],
   e:["µg/m³ = concentration in micrograms per cubic metre at normal atmospheric conditions, i.e. pressure (P) 1 atm and temperature (T) 25 °C.",
      "# The concentration reported for a 1-hour averaging time is measured every 30 minutes — 2 measurements within the hour — taken between 11:00 and 14:00 local time.",
      "## The concentration reported for an 8-hour averaging time is derived from measurements taken between 06:00 and 18:00 local time.",
      "### The concentration reported for a 3-hour averaging time is derived from measurements taken between 06:00 and 10:00 local time."],
   z:["µg/m³ = 标准大气条件下（压力 P = 1 atm，温度 T = 25 °C）每立方米微克数的浓度。",
      "# 1 小时时段所报浓度为每 30 分钟测量一次（1 小时内测 2 次）的结果，且须在当地时间 11:00–14:00 之间进行。",
      "## 8 小时时段所报浓度取自当地时间 06:00–18:00 之间进行的测量。",
      "### 3 小时时段所报浓度取自当地时间 06:00–10:00 之间进行的测量。"]
  }
},

sea:{
  code:"PP 22/2021 Lampiran VIII",
  title:{i:"Baku Mutu Air Laut",e:"Sea Water Quality Standard",z:"海水水质标准"},
  cols:{i:["No","Parameter","Satuan","Pelabuhan","Wisata Bahari","Biota Laut"],
        e:["No","Parameter","Unit","Port","Marine Tourism","Marine Biota"],
        z:["序号","参数","单位","港口","海洋旅游","海洋生物"]},
  rows:[
   {n:"1",p:{i:"Warna",e:"Colour",z:"色度"},u:"Pt-Co",v:["—","30","—"],k:{i:"",e:"",z:""}},
   {n:"2",p:{i:"Kecerahan",e:"Water clarity",z:"水体清澈度"},u:"m",v:[">3",">6","coral: >5 · mangrove: — · lamun: >3"],k:{i:"",e:"",z:""}},
   {n:"3",p:{i:"Kekeruhan",e:"Turbidity",z:"浊度"},u:"NTU",v:["—","5","5"],k:{i:"",e:"",z:""}},
   {n:"4",p:{i:"Kebauan",e:"Odour",z:"嗅"},u:"—",v:["tidak berbau","tidak berbau","alami"],k:{i:"",e:"",z:""}},
   {n:"5",p:{i:"Padatan tersuspensi total",e:"Total Suspended Solids",z:"总悬浮物"},u:"mg/L",v:["80","20","coral: 20 · mangrove: 80 · lamun: 20"],k:{i:"",e:"",z:""}},
   {n:"6",p:{i:"Sampah",e:"Refuse / Litter",z:"垃圾"},u:"—",v:["nihil","nihil","nihil"],k:{i:"",e:"",z:""}},
   {n:"7",p:{i:"Suhu",e:"Temperature",z:"水温"},u:"°C",v:["alami","alami","alami · coral: 28-30 · mangrove: 28-32 · lamun: 28-30"],k:{i:"",e:"",z:""}},
   {n:"8",p:{i:"Lapisan minyak",e:"Oil film",z:"浮油"},u:"—",v:["nihil","nihil","nihil"],k:{i:"",e:"",z:""}},
   {n:"9",p:{i:"pH",e:"pH",z:"pH 值"},u:"—",v:["6,5 – 8,5","7 – 8,5","7 – 8,5"],k:{i:"",e:"",z:""}},
   {n:"10",p:{i:"Salinitas",e:"Salinity",z:"盐度"},u:"‰",v:["alami","alami","alami · coral: 33-34 · mangrove: s/d 34 · lamun: 33-34"],k:{i:"",e:"",z:""}},
   {n:"11",p:{i:"Oksigen terlarut (DO)",e:"Dissolved Oxygen (DO)",z:"溶解氧 (DO)"},u:"mg/L",v:["—",">5",">5"],k:{i:"",e:"",z:""}},
   {n:"12",p:{i:"BOD₅",e:"BOD₅",z:"五日生化需氧量 (BOD₅)"},u:"mg/L",v:["—","10","20"],k:{i:"",e:"",z:""}},
   {n:"13",p:{i:"Amonia total (NH₃-N)",e:"Total Ammonia (NH₃-N)",z:"总氨氮 (NH₃-N)"},u:"mg/L",v:["0,3","0,02","0,3"],k:{i:"",e:"",z:""}},
   {n:"14",p:{i:"Ortofosfat (PO₄-P)",e:"Orthophosphate (PO₄-P)",z:"正磷酸盐 (PO₄-P)"},u:"mg/L",v:["—","0,015","0,015"],k:{i:"",e:"",z:""}},
   {n:"15",p:{i:"Nitrat (NO₃-N)",e:"Nitrate (NO₃-N)",z:"硝酸盐 (NO₃-N)"},u:"mg/L",v:["—","0,06","0,06"],k:{i:"",e:"",z:""}},
   {n:"16",p:{i:"Sianida (CN⁻)",e:"Cyanide (CN⁻)",z:"氰化物 (CN⁻)"},u:"mg/L",v:["—","—","0,5"],k:{i:"",e:"",z:""}},
   {n:"17",p:{i:"Sulfida (H₂S)",e:"Sulphide (H₂S)",z:"硫化物 (H₂S)"},u:"mg/L",v:["0,03","0,002","0,01"],k:{i:"",e:"",z:""}},
   {n:"18",p:{i:"Hidrokarbon Petroleum Total (TPH)",e:"Total Petroleum Hydrocarbons (TPH)",z:"石油烃总量 (TPH)"},u:"mg/L",v:["1","—","0,02"],k:{i:"",e:"",z:""}},
   {n:"19",p:{i:"Senyawa Fenol total",e:"Total Phenolic Compounds",z:"总酚"},u:"mg/L",v:["0,002","0,001","0,002"],k:{i:"",e:"",z:""}},
   {n:"20",p:{i:"PAH (Poliaromatik hidrokarbon)",e:"PAH (Polyaromatic Hydrocarbons)",z:"多环芳烃 (PAH)"},u:"mg/L",v:["—","0,003","0,003"],k:{i:"",e:"",z:""}},
   {n:"21",p:{i:"PCB (poliklor bifenil)",e:"PCB (Polychlorinated Biphenyls)",z:"多氯联苯 (PCB)"},u:"µg/L",v:["0,01","0,005","0,01"],k:{i:"",e:"",z:""}},
   {n:"22",p:{i:"Surfaktan (deterjen) sebagai MBAS",e:"Surfactant (detergent) as MBAS",z:"表面活性剂（以 MBAS 计）"},u:"mg/L",v:["1","0,001","1"],k:{i:"",e:"",z:""}},
   {n:"23",p:{i:"Minyak dan Lemak",e:"Oil and Grease",z:"石油类与油脂"},u:"mg/L",v:["5","1","1"],k:{i:"",e:"",z:""}},
   {n:"24a",p:{i:"Pestisida — BHC",e:"Pesticide — BHC",z:"农药 — 六六六 (BHC)"},u:"µg/L",v:["—","210","210"],k:{i:"",e:"",z:""}},
   {n:"24b",p:{i:"Pestisida — Aldrin/Dieldrin",e:"Pesticide — Aldrin/Dieldrin",z:"农药 — 艾氏剂/狄氏剂"},u:"µg/L",v:["—","17","—"],k:{i:"",e:"",z:""}},
   {n:"24c",p:{i:"Pestisida — Chlordane",e:"Pesticide — Chlordane",z:"农药 — 氯丹"},u:"µg/L",v:["—","3","—"],k:{i:"",e:"",z:""}},
   {n:"24d",p:{i:"Pestisida — DDT",e:"Pesticide — DDT",z:"农药 — 滴滴涕 (DDT)"},u:"µg/L",v:["—","2","2"],k:{i:"",e:"",z:""}},
   {n:"24e",p:{i:"Pestisida — Heptachlor",e:"Pesticide — Heptachlor",z:"农药 — 七氯"},u:"µg/L",v:["—","18","—"],k:{i:"",e:"",z:""}},
   {n:"24f",p:{i:"Pestisida — Lindane",e:"Pesticide — Lindane",z:"农药 — 林丹"},u:"µg/L",v:["—","56","—"],k:{i:"",e:"",z:""}},
   {n:"24g",p:{i:"Pestisida — Methoxychlor",e:"Pesticide — Methoxychlor",z:"农药 — 甲氧滴滴涕"},u:"µg/L",v:["—","35","—"],k:{i:"",e:"",z:""}},
   {n:"24h",p:{i:"Pestisida — Endrin",e:"Pesticide — Endrin",z:"农药 — 异狄氏剂"},u:"µg/L",v:["—","1","4"],k:{i:"",e:"",z:""}},
   {n:"24i",p:{i:"Pestisida — Toxaphan",e:"Pesticide — Toxaphene",z:"农药 — 毒杀芬"},u:"µg/L",v:["—","5","—"],k:{i:"",e:"",z:""}},
   {n:"25",p:{i:"TBT (tri butil tin)",e:"TBT (Tributyltin)",z:"三丁基锡 (TBT)"},u:"µg/L",v:["0,01","—","0,01"],k:{i:"",e:"",z:""}},
   {n:"26",p:{i:"Raksa (Hg)",e:"Mercury (Hg)",z:"汞 (Hg)"},u:"mg/L",v:["0,003","0,002","0,001"],k:{i:"",e:"",z:""}},
   {n:"27",p:{i:"Kromium heksavalen (Cr(VI))",e:"Hexavalent Chromium (Cr(VI))",z:"六价铬 (Cr(VI))"},u:"mg/L",v:["—","0,002","0,005"],k:{i:"",e:"",z:""}},
   {n:"28",p:{i:"Arsen (As)",e:"Arsenic (As)",z:"砷 (As)"},u:"mg/L",v:["—","0,025","0,012"],k:{i:"",e:"",z:""}},
   {n:"29",p:{i:"Kadmium (Cd)",e:"Cadmium (Cd)",z:"镉 (Cd)"},u:"mg/L",v:["0,01","0,002","0,001"],k:{i:"",e:"",z:""}},
   {n:"30",p:{i:"Tembaga (Cu)",e:"Copper (Cu)",z:"铜 (Cu)"},u:"mg/L",v:["0,05","0,05","0,008"],k:{i:"",e:"",z:""}},
   {n:"31",p:{i:"Timbal (Pb)",e:"Lead (Pb)",z:"铅 (Pb)"},u:"mg/L",v:["0,05","0,005","0,008"],k:{i:"",e:"",z:""}},
   {n:"32",p:{i:"Seng (Zn)",e:"Zinc (Zn)",z:"锌 (Zn)"},u:"mg/L",v:["0,1","0,095","0,05"],k:{i:"",e:"",z:""}},
   {n:"33",p:{i:"Nikel (Ni)",e:"Nickel (Ni)",z:"镍 (Ni)"},u:"mg/L",v:["—","0,075","0,05"],k:{i:"",e:"",z:""}},
   {n:"34",p:{i:"Fecal coliform",e:"Faecal coliform",z:"粪大肠菌群"},u:"Jml/100 mL",v:["—","200","—"],k:{i:"",e:"",z:""}},
   {n:"35",p:{i:"Coliform (total)",e:"Coliform (total)",z:"总大肠菌群"},u:"Jml/100 mL",v:["1000","1000","1000"],k:{i:"",e:"",z:""}},
   {n:"36",p:{i:"Patogen",e:"Pathogens",z:"病原体"},u:"sel/100 mL",v:["—","nihil","nihil"],k:{i:"",e:"",z:""}},
   {n:"37",p:{i:"Fitoplankton",e:"Phytoplankton",z:"浮游植物"},u:"sel/mL",v:["—","1000","1000"],k:{i:"",e:"",z:""}},
   {n:"38",p:{i:"Radioaktifitas",e:"Radioactivity",z:"放射性"},u:"Bq/L",v:["—","4","4"],k:{i:"",e:"",z:""}}
  ],
  foot:{
   i:["\"Alami\" adalah kondisi normal suatu lingkungan yang bervariasi setiap saat (siang/malam) sesuai keadaan alaminya, dipakai sebagai acuan.",
      "coral / mangrove / lamun = nilai khusus untuk peruntukan terumbu karang, hutan bakau, dan padang lamun.",
      "Nilai \"nihil\" berarti tidak boleh terdeteksi; \"s/d\" berarti sampai dengan.",
      "Catatan lengkap mengenai fitoplankton dan Harmful Algae Bloom (HAB) tercantum pada keterangan Lampiran VIII — teks aslinya sebagian tidak terbaca pada salinan PDF; rujuk dokumen resmi untuk kutipan verbatim."],
   e:["\"Alami\" (natural) means the normal condition of an environment which varies naturally through the day and night; it is used as the reference.",
      "coral / mangrove / lamun = specific values for coral reef, mangrove and seagrass designations respectively.",
      "\"nihil\" means it must not be detectable; \"s/d\" means \"up to\".",
      "The full note on phytoplankton and Harmful Algae Bloom (HAB) appears in the Lampiran VIII remarks — parts of the original are illegible in the PDF copy; consult the official document for a verbatim citation."],
   z:["\"Alami\"（天然）指环境的正常状态，随昼夜自然变化，以此作为基准。",
      "coral / mangrove / lamun = 分别对应珊瑚礁、红树林与海草床用途的专用限值。",
      "\"nihil\" 表示不得检出；\"s/d\" 表示\"至\"。",
      "关于浮游植物与有害藻华（HAB）的完整说明见附件 VIII 备注 — PDF 副本中该段原文部分不可辨识，逐字引用请查阅官方文件。"]
  }
},

// ── Lampiran XI — TCLP limits that decide the B3 waste category ──
b3_tclp:{
  code:"PP 22/2021 Lampiran XI",
  title:{i:"Baku Mutu TCLP untuk Penetapan Kategori Limbah B3",e:"TCLP Limits for Determining B3 Hazardous-Waste Category",z:"用于判定 B3 危险废物类别的 TCLP 标准限值"},
  cols:{i:["No","Zat Pencemar","Satuan","TCLP-A (mg/L)","TCLP-B (mg/L)","Kelompok"],
        e:["No","Contaminant","Unit","TCLP-A (mg/L)","TCLP-B (mg/L)","Group"],
        z:["序号","污染物","单位","TCLP-A (mg/L)","TCLP-B (mg/L)","类别"]},
  rows:[
   {n:"1",p:{i:"Antimoni, Sb",e:"Antimony, Sb",z:"锑 Sb"},u:"mg/L",v:["6","1"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"2",p:{i:"Arsen, As",e:"Arsenic, As",z:"砷 As"},u:"mg/L",v:["3","0,5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"3",p:{i:"Barium, Ba",e:"Barium, Ba",z:"钡 Ba"},u:"mg/L",v:["210","35"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"4",p:{i:"Berilium, Be",e:"Beryllium, Be",z:"铍 Be"},u:"mg/L",v:["4","0,5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"5",p:{i:"Boron, B",e:"Boron, B",z:"硼 B"},u:"mg/L",v:["150","25"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"6",p:{i:"Kadmium, Cd",e:"Cadmium, Cd",z:"镉 Cd"},u:"mg/L",v:["0,9","0,15"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"7",p:{i:"Krom valensi enam, Cr⁶⁺",e:"Hexavalent Chromium, Cr⁶⁺",z:"六价铬 Cr⁶⁺"},u:"mg/L",v:["15","2,5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"8",p:{i:"Tembaga, Cu",e:"Copper, Cu",z:"铜 Cu"},u:"mg/L",v:["60","10"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"9",p:{i:"Timbal, Pb",e:"Lead, Pb",z:"铅 Pb"},u:"mg/L",v:["3","0,5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"10",p:{i:"Merkuri, Hg",e:"Mercury, Hg",z:"汞 Hg"},u:"mg/L",v:["0,3","0,05"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"11",p:{i:"Molibdenum, Mo",e:"Molybdenum, Mo",z:"钼 Mo"},u:"mg/L",v:["21","3,5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"12",p:{i:"Nikel, Ni",e:"Nickel, Ni",z:"镍 Ni"},u:"mg/L",v:["21","3,5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"13",p:{i:"Selenium, Se",e:"Selenium, Se",z:"硒 Se"},u:"mg/L",v:["3","0,5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"14",p:{i:"Perak, Ag",e:"Silver, Ag",z:"银 Ag"},u:"mg/L",v:["40","5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"15",p:{i:"Tributyltin oxide",e:"Tributyltin oxide",z:"三丁基锡氧化物"},u:"mg/L",v:["0,4","0,05"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"16",p:{i:"Seng, Zn",e:"Zinc, Zn",z:"锌 Zn"},u:"mg/L",v:["300","50"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"17",p:{i:"Klorida, Cl⁻",e:"Chloride, Cl⁻",z:"氯化物 Cl⁻"},u:"mg/L",v:["75.000","12.500"],k:{i:"Anion",e:"Anion",z:"阴离子"}},
   {n:"18",p:{i:"Sianida (total), CN⁻",e:"Cyanide (total), CN⁻",z:"氰化物（总）CN⁻"},u:"mg/L",v:["21","3,5"],k:{i:"Anion",e:"Anion",z:"阴离子"}},
   {n:"19",p:{i:"Fluorida, F⁻",e:"Fluoride, F⁻",z:"氟化物 F⁻"},u:"mg/L",v:["450","75"],k:{i:"Anion",e:"Anion",z:"阴离子"}},
   {n:"20",p:{i:"Iodida, I⁻",e:"Iodide, I⁻",z:"碘化物 I⁻"},u:"mg/L",v:["40","5"],k:{i:"Anion",e:"Anion",z:"阴离子"}},
   {n:"21",p:{i:"Nitrat, NO₃⁻",e:"Nitrate, NO₃⁻",z:"硝酸盐 NO₃⁻"},u:"mg/L",v:["15.000","2.500"],k:{i:"Anion",e:"Anion",z:"阴离子"}},
   {n:"22",p:{i:"Nitrit, NO₂⁻",e:"Nitrite, NO₂⁻",z:"亚硝酸盐 NO₂⁻"},u:"mg/L",v:["900","150"],k:{i:"Anion",e:"Anion",z:"阴离子"}},
   {n:"23",p:{i:"Benzena",e:"Benzene",z:"苯"},u:"mg/L",v:["3","0,5"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"24",p:{i:"Benzo(a)pirena",e:"Benzo(a)pyrene",z:"苯并(a)芘"},u:"mg/L",v:["0,004","0,0005"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"25",p:{i:"Karbon tetraklorida",e:"Carbon tetrachloride",z:"四氯化碳"},u:"mg/L",v:["1,2","0,2"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"26",p:{i:"Klorobenzena",e:"Chlorobenzene",z:"氯苯"},u:"mg/L",v:["120","15"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"27",p:{i:"Kloroform",e:"Chloroform",z:"氯仿"},u:"mg/L",v:["24","3"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"28",p:{i:"2-Klorofenol",e:"2-Chlorophenol",z:"2-氯苯酚"},u:"mg/L",v:["120","5"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"29",p:{i:"Kresol (total)",e:"Cresol (total)",z:"甲酚（总）"},u:"mg/L",v:["800","100"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"30",p:{i:"Di(2-etilheksil) ftalat",e:"Di(2-ethylhexyl) phthalate",z:"邻苯二甲酸二(2-乙基己基)酯"},u:"mg/L",v:["24","0,4"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"31",p:{i:"1,2-Diklorobenzena",e:"1,2-Dichlorobenzene",z:"1,2-二氯苯"},u:"mg/L",v:["300","50"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"32",p:{i:"1,4-Diklorobenzena",e:"1,4-Dichlorobenzene",z:"1,4-二氯苯"},u:"mg/L",v:["90","15"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"33",p:{i:"1,2-Dikloroetana",e:"1,2-Dichloroethane",z:"1,2-二氯乙烷"},u:"mg/L",v:["15","2,5"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"34",p:{i:"1,1-Dikloroetena",e:"1,1-Dichloroethene",z:"1,1-二氯乙烯"},u:"mg/L",v:["12","3"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"35",p:{i:"1,2-Dikloroetena",e:"1,2-Dichloroethene",z:"1,2-二氯乙烯"},u:"mg/L",v:["15","2,5"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"36",p:{i:"Diklorometana (metilen klorida)",e:"Dichloromethane (methylene chloride)",z:"二氯甲烷"},u:"mg/L",v:["6","1"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"37",p:{i:"2,4-Diklorofenol",e:"2,4-Dichlorophenol",z:"2,4-二氯苯酚"},u:"mg/L",v:["80","10"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"38",p:{i:"2,4-Dinitrotoluena",e:"2,4-Dinitrotoluene",z:"2,4-二硝基甲苯"},u:"mg/L",v:["0,52","0,065"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"39",p:{i:"Etilbenzena",e:"Ethylbenzene",z:"乙苯"},u:"mg/L",v:["90","15"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"40",p:{i:"EDTA (ethylene diamine tetra acetic acid)",e:"EDTA (ethylenediaminetetraacetic acid)",z:"乙二胺四乙酸 (EDTA)"},u:"mg/L",v:["180","30"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"41",p:{i:"Formaldehida",e:"Formaldehyde",z:"甲醛"},u:"mg/L",v:["200","25"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"42",p:{i:"Heksaklorobutadiena",e:"Hexachlorobutadiene",z:"六氯丁二烯"},u:"mg/L",v:["0,18","0,03"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"43",p:{i:"Metil etil keton",e:"Methyl ethyl ketone",z:"甲乙酮"},u:"mg/L",v:["800","100"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"44",p:{i:"Nitrobenzena",e:"Nitrobenzene",z:"硝基苯"},u:"mg/L",v:["8","1"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"45",p:{i:"Fenol (total, non-terhalogenasi)",e:"Phenol (total, non-halogenated)",z:"酚（总，非卤代）"},u:"mg/L",v:["56","7"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"46",p:{i:"Stirena",e:"Styrene",z:"苯乙烯"},u:"mg/L",v:["6","1"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"47",p:{i:"1,1,1,2-Tetrakloroetana",e:"1,1,1,2-Tetrachloroethane",z:"1,1,1,2-四氯乙烷"},u:"mg/L",v:["40","4"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"48",p:{i:"1,1,2,2-Tetrakloroetana",e:"1,1,2,2-Tetrachloroethane",z:"1,1,2,2-四氯乙烷"},u:"mg/L",v:["5,2","0,65"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"49",p:{i:"Tetrakloroetena",e:"Tetrachloroethene",z:"四氯乙烯"},u:"mg/L",v:["20","2,5"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"50",p:{i:"Toluena",e:"Toluene",z:"甲苯"},u:"mg/L",v:["210","35"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"51",p:{i:"Triklorobenzena (total)",e:"Trichlorobenzene (total)",z:"三氯苯（总）"},u:"mg/L",v:["12","1,5"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"52",p:{i:"1,1,1-Trikloroetana",e:"1,1,1-Trichloroethane",z:"1,1,1-三氯乙烷"},u:"mg/L",v:["120","15"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"53",p:{i:"1,1,2-Trikloroetana",e:"1,1,2-Trichloroethane",z:"1,1,2-三氯乙烷"},u:"mg/L",v:["4,8","0,6"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"54",p:{i:"Trikloroetena",e:"Trichloroethene",z:"三氯乙烯"},u:"mg/L",v:["2","0,25"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"55",p:{i:"2,4,5-Triklorofenol",e:"2,4,5-Trichlorophenol",z:"2,4,5-三氯苯酚"},u:"mg/L",v:["1.600","200"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"56",p:{i:"2,4,6-Triklorofenol",e:"2,4,6-Trichlorophenol",z:"2,4,6-三氯苯酚"},u:"mg/L",v:["8","1"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"57",p:{i:"Vinil klorida",e:"Vinyl chloride",z:"氯乙烯"},u:"mg/L",v:["0,12","0,015"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"58",p:{i:"Ksilena (total)",e:"Xylene (total)",z:"二甲苯（总）"},u:"mg/L",v:["150","25"],k:{i:"Organik",e:"Organic",z:"有机物"}},
   {n:"59",p:{i:"Aldrin + dieldrin",e:"Aldrin + dieldrin",z:"艾氏剂 + 狄氏剂"},u:"mg/L",v:["0,009","0,0015"],k:{i:"Pestisida",e:"Pesticide",z:"农药"}},
   {n:"60",p:{i:"DDT + DDD + DDE",e:"DDT + DDD + DDE",z:"DDT + DDD + DDE"},u:"mg/L",v:["0,3","0,05"],k:{i:"Pestisida",e:"Pesticide",z:"农药"}},
   {n:"61",p:{i:"2,4-D",e:"2,4-D",z:"2,4-滴"},u:"mg/L",v:["9","1,5"],k:{i:"Pestisida",e:"Pesticide",z:"农药"}},
   {n:"62",p:{i:"Klordana",e:"Chlordane",z:"氯丹"},u:"mg/L",v:["0,06","0,01"],k:{i:"Pestisida",e:"Pesticide",z:"农药"}},
   {n:"63",p:{i:"Heptaklor",e:"Heptachlor",z:"七氯"},u:"mg/L",v:["0,12","0,015"],k:{i:"Pestisida",e:"Pesticide",z:"农药"}},
   {n:"64",p:{i:"Lindana",e:"Lindane",z:"林丹"},u:"mg/L",v:["0,6","0,1"],k:{i:"Pestisida",e:"Pesticide",z:"农药"}},
   {n:"65",p:{i:"Metoksiklor",e:"Methoxychlor",z:"甲氧滴滴涕"},u:"mg/L",v:["6","1"],k:{i:"Pestisida",e:"Pesticide",z:"农药"}},
   {n:"66",p:{i:"Pentaklorofenol",e:"Pentachlorophenol",z:"五氯苯酚"},u:"mg/L",v:["2,7","0,45"],k:{i:"Pestisida",e:"Pesticide",z:"农药"}},
   {n:"67",p:{i:"Endrin",e:"Endrin",z:"异狄氏剂"},u:"mg/L",v:["0,12","0,02"],k:{i:"Parameter tambahan",e:"Additional parameter",z:"附加参数"}},
   {n:"68",p:{i:"Heksaklorobenzena",e:"Hexachlorobenzene",z:"六氯苯"},u:"mg/L",v:["0,8","0,13"],k:{i:"Parameter tambahan",e:"Additional parameter",z:"附加参数"}},
   {n:"69",p:{i:"Heksakloroetana",e:"Hexachloroethane",z:"六氯乙烷"},u:"mg/L",v:["18","3"],k:{i:"Parameter tambahan",e:"Additional parameter",z:"附加参数"}},
   {n:"70",p:{i:"Piridina",e:"Pyridine",z:"吡啶"},u:"mg/L",v:["30","5"],k:{i:"Parameter tambahan",e:"Additional parameter",z:"附加参数"}},
   {n:"71",p:{i:"Toksafena",e:"Toxaphene",z:"毒杀芬"},u:"mg/L",v:["3","0,5"],k:{i:"Parameter tambahan",e:"Additional parameter",z:"附加参数"}},
   {n:"72",p:{i:"2,4,5-TP (Silvex)",e:"2,4,5-TP (Silvex)",z:"2,4,5-涕丙酸 (Silvex)"},u:"mg/L",v:["6","1"],k:{i:"Parameter tambahan",e:"Additional parameter",z:"附加参数"}}
  ],
  foot:{
   i:["Satuan dinyatakan dalam berat kering. Limbah dengan konsentrasi TCLP di atas TCLP-A dikategorikan Limbah B3 Kategori 1; di antara TCLP-A dan TCLP-B dikategorikan Kategori 2.",
      "Analisis terhadap parameter tambahan dilakukan secara langsung (purposive) terhadap Limbah yang mengandung zat pencemar dimaksud.",
      "Nilai disalin dari PDF resmi (lapisan teks hasil OCR) dan diperiksa silang dengan dua mode ekstraksi. Untuk keputusan kepatuhan yang mengikat, verifikasi terhadap dokumen asli."],
   e:["Units are on a dry-weight basis. Waste with a TCLP concentration above TCLP-A is classified as Category 1 B3 waste; between TCLP-A and TCLP-B it is Category 2.",
      "Additional parameters are tested purposively — only on waste known to contain that contaminant.",
      "Values were transcribed from the official PDF (an OCR-derived text layer) and cross-checked with two independent extraction modes. For binding compliance decisions, verify against the original document."],
   z:["单位以干重计。TCLP 浓度高于 TCLP-A 的废物判定为第 1 类 B3 危险废物；介于 TCLP-A 与 TCLP-B 之间的判定为第 2 类。",
      "附加参数采取针对性检测 — 仅对已知含该污染物的废物进行分析。",
      "数值转录自官方 PDF（OCR 生成的文本层），并以两种独立提取模式交叉核对。用于具有约束力的合规判定时，请以原始文件为准。"]
  }
},

// ── Lampiran XII — TCLP limit before landfilling ──
b3_landfill:{
  code:"PP 22/2021 Lampiran XII",
  title:{i:"Baku Mutu TCLP — Standar Pengolahan Limbah B3 Sebelum Penimbusan Akhir",e:"TCLP Limits — B3 Waste Treatment Standard Before Final Landfilling",z:"TCLP 标准限值 — B3 危险废物最终填埋前的处理标准"},
  cols:{i:["No","Zat Pencemar","Satuan","TCLP (mg/L)","Kelompok"],
        e:["No","Contaminant","Unit","TCLP (mg/L)","Group"],
        z:["序号","污染物","单位","TCLP (mg/L)","类别"]},
  rows:[
   {n:"1",p:{i:"Antimoni, Sb",e:"Antimony, Sb",z:"锑 Sb"},u:"mg/L",v:["1"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"2",p:{i:"Arsen, As",e:"Arsenic, As",z:"砷 As"},u:"mg/L",v:["0,5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"3",p:{i:"Barium, Ba",e:"Barium, Ba",z:"钡 Ba"},u:"mg/L",v:["35"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"4",p:{i:"Berilium, Be",e:"Beryllium, Be",z:"铍 Be"},u:"mg/L",v:["0,5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"5",p:{i:"Boron, B",e:"Boron, B",z:"硼 B"},u:"mg/L",v:["25"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"6",p:{i:"Kadmium, Cd",e:"Cadmium, Cd",z:"镉 Cd"},u:"mg/L",v:["0,15"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"7",p:{i:"Krom valensi enam, Cr⁶⁺",e:"Hexavalent Chromium, Cr⁶⁺",z:"六价铬 Cr⁶⁺"},u:"mg/L",v:["2,5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"8",p:{i:"Tembaga, Cu",e:"Copper, Cu",z:"铜 Cu"},u:"mg/L",v:["10"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"9",p:{i:"Timbal, Pb",e:"Lead, Pb",z:"铅 Pb"},u:"mg/L",v:["0,5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"10",p:{i:"Merkuri, Hg",e:"Mercury, Hg",z:"汞 Hg"},u:"mg/L",v:["0,05"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"11",p:{i:"Molibdenum, Mo",e:"Molybdenum, Mo",z:"钼 Mo"},u:"mg/L",v:["3,5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"12",p:{i:"Nikel, Ni",e:"Nickel, Ni",z:"镍 Ni"},u:"mg/L",v:["3,5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"13",p:{i:"Selenium, Se",e:"Selenium, Se",z:"硒 Se"},u:"mg/L",v:["0,5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"14",p:{i:"Perak, Ag",e:"Silver, Ag",z:"银 Ag"},u:"mg/L",v:["5"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"15",p:{i:"Tributyltin oxide",e:"Tributyltin oxide",z:"三丁基锡氧化物"},u:"mg/L",v:["0,05"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"16",p:{i:"Seng, Zn",e:"Zinc, Zn",z:"锌 Zn"},u:"mg/L",v:["50"],k:{i:"Anorganik",e:"Inorganic",z:"无机物"}},
   {n:"17",p:{i:"Klorida, Cl⁻",e:"Chloride, Cl⁻",z:"氯化物 Cl⁻"},u:"mg/L",v:["12.500"],k:{i:"Anion",e:"Anion",z:"阴离子"}},
   {n:"18",p:{i:"Sianida (total), CN⁻",e:"Cyanide (total), CN⁻",z:"氰化物（总）CN⁻"},u:"mg/L",v:["3,5"],k:{i:"Anion",e:"Anion",z:"阴离子"}},
   {n:"19",p:{i:"Fluorida, F⁻",e:"Fluoride, F⁻",z:"氟化物 F⁻"},u:"mg/L",v:["75"],k:{i:"Anion",e:"Anion",z:"阴离子"}},
   {n:"20",p:{i:"Iodida, I⁻",e:"Iodide, I⁻",z:"碘化物 I⁻"},u:"mg/L",v:["5"],k:{i:"Anion",e:"Anion",z:"阴离子"}},
   {n:"21",p:{i:"Nitrat, NO₃⁻",e:"Nitrate, NO₃⁻",z:"硝酸盐 NO₃⁻"},u:"mg/L",v:["2.500"],k:{i:"Anion",e:"Anion",z:"阴离子"}},
   {n:"22",p:{i:"Nitrit, NO₂⁻",e:"Nitrite, NO₂⁻",z:"亚硝酸盐 NO₂⁻"},u:"mg/L",v:["150"],k:{i:"Anion",e:"Anion",z:"阴离子"}}
  ],
  foot:{
   i:["Tabel ini memuat parameter anorganik dan anion. Nilai TCLP pada Lampiran XII identik dengan kolom <strong>TCLP-B</strong> pada Lampiran XI — limbah harus diolah hingga memenuhi nilai ini sebelum ditempatkan di fasilitas penimbusan akhir (landfill).",
      "Parameter organik dan pestisida mengikuti nilai TCLP-B Lampiran XI; lihat tabel Lampiran XI untuk daftar lengkapnya.",
      "Satuan dinyatakan dalam berat kering."],
   e:["This table lists the inorganic and anion parameters. The Lampiran XII TCLP values are identical to the <strong>TCLP-B</strong> column of Lampiran XI — waste must be treated down to these values before it may be placed in a final landfill facility.",
      "Organic and pesticide parameters follow the Lampiran XI TCLP-B values; see the Lampiran XI table for the complete list.",
      "Units are on a dry-weight basis."],
   z:["本表列出无机物与阴离子参数。附件 XII 的 TCLP 限值与附件 XI 的 <strong>TCLP-B</strong> 栏一致 — 废物须处理至该限值方可进入最终填埋设施。",
      "有机物与农药参数沿用附件 XI 的 TCLP-B 值，完整清单见附件 XI 表格。",
      "单位以干重计。"]
  }
},

// ── Lampiran XIII — contaminated-soil management thresholds ──
b3_soil:{
  code:"PP 22/2021 Lampiran XIII",
  title:{i:"Baku Karakteristik Beracun TCLP & Total Konsentrasi — Tanah Terkontaminasi Limbah B3",e:"TCLP & Total Concentration Thresholds — Soil Contaminated by B3 Waste",z:"TCLP 与总浓度限值 — B3 危险废物污染土壤"},
  cols:{i:["No","Zat Pencemar","Satuan","TCLP-A (mg/L)","TK-A (mg/kg)","TCLP-B (mg/L)","TK-B (mg/kg)","TCLP-C (mg/L)","TK-C (mg/kg)"],
        e:["No","Contaminant","Unit","TCLP-A (mg/L)","TK-A (mg/kg)","TCLP-B (mg/L)","TK-B (mg/kg)","TCLP-C (mg/L)","TK-C (mg/kg)"],
        z:["序号","污染物","单位","TCLP-A (mg/L)","TK-A (mg/kg)","TCLP-B (mg/L)","TK-B (mg/kg)","TCLP-C (mg/L)","TK-C (mg/kg)"]},
  rows:[
   {n:"1",p:{i:"Antimoni, Sb",e:"Antimony, Sb",z:"锑 Sb"},u:"—",v:["6","300","1","75","0,4","3"],k:{i:"",e:"",z:""}},
   {n:"2",p:{i:"Arsen, As",e:"Arsenic, As",z:"砷 As"},u:"—",v:["3","2.000","0,5","500","0,2","20"],k:{i:"",e:"",z:""}},
   {n:"3",p:{i:"Barium, Ba",e:"Barium, Ba",z:"钡 Ba"},u:"—",v:["210","25.000","35","6.250","1,4","160"],k:{i:"",e:"",z:""}},
   {n:"4",p:{i:"Berilium, Be",e:"Beryllium, Be",z:"铍 Be"},u:"—",v:["4","4.000","0,5","100","0,2","1,1"],k:{i:"",e:"",z:""}},
   {n:"5",p:{i:"Boron, B",e:"Boron, B",z:"硼 B"},u:"—",v:["150","60.000","25","15.000","10","36"],k:{i:"",e:"",z:""}},
   {n:"6",p:{i:"Kadmium, Cd",e:"Cadmium, Cd",z:"镉 Cd"},u:"—",v:["0,9","400","0,15","100","0,06","3"],k:{i:"",e:"",z:""}},
   {n:"7",p:{i:"Krom valensi enam, Cr⁶⁺",e:"Hexavalent Chromium, Cr⁶⁺",z:"六价铬 Cr⁶⁺"},u:"—",v:["15","2.000","2,5","500","1","1"],k:{i:"",e:"",z:""}},
   {n:"8",p:{i:"Tembaga, Cu",e:"Copper, Cu",z:"铜 Cu"},u:"—",v:["60","3.000","10","750","4","30"],k:{i:"",e:"",z:""}},
   {n:"9",p:{i:"Timbal, Pb",e:"Lead, Pb",z:"铅 Pb"},u:"—",v:["3","6.000","0,5","1.500","0,2","300"],k:{i:"",e:"",z:""}},
   {n:"10",p:{i:"Merkuri, Hg",e:"Mercury, Hg",z:"汞 Hg"},u:"—",v:["0,3","300","0,05","75","0,02","0,3"],k:{i:"",e:"",z:""}},
   {n:"11",p:{i:"Molibdenum, Mo",e:"Molybdenum, Mo",z:"钼 Mo"},u:"—",v:["21","4.000","3,5","1.000","1,4","40"],k:{i:"",e:"",z:""}},
   {n:"12",p:{i:"Nikel, Ni",e:"Nickel, Ni",z:"镍 Ni"},u:"—",v:["21","12.000","3,5","3.000","1,4","60"],k:{i:"",e:"",z:""}},
   {n:"13",p:{i:"Selenium, Se",e:"Selenium, Se",z:"硒 Se"},u:"—",v:["3","200","0,5","50","0,2","10"],k:{i:"",e:"",z:""}},
   {n:"14",p:{i:"Perak, Ag",e:"Silver, Ag",z:"银 Ag"},u:"—",v:["40","720","5","180","2","10"],k:{i:"",e:"",z:""}}
  ],
  foot:{
   i:["TCLP = uji pelindian (leaching); TK = Total Konsentrasi. Kategori A/B/C menentukan tindakan pengelolaan tanah terkontaminasi: melampaui nilai A menuntut penanganan sebagai Limbah B3 Kategori 1, di antara A dan B sebagai Kategori 2, dan di bawah C dapat dikelola sebagai tanah tidak terkontaminasi.",
      "Tabel ini memuat parameter <strong>anorganik wajib</strong>. Parameter anion, organik, pestisida, dan parameter tambahan mengikuti struktur yang sama pada dokumen asli.",
      "Nilai disalin dari PDF resmi (lapisan teks hasil OCR). Untuk keputusan kepatuhan yang mengikat, verifikasi terhadap dokumen asli Lampiran XIII."],
   e:["TCLP = leaching test; TK (Total Konsentrasi) = total concentration. Categories A/B/C determine how contaminated soil must be managed: above the A values it is handled as Category 1 B3 waste, between A and B as Category 2, and below C it may be managed as uncontaminated soil.",
      "This table carries the <strong>mandatory inorganic</strong> parameters. Anion, organic, pesticide and additional parameters follow the same structure in the source document.",
      "Values were transcribed from the official PDF (an OCR-derived text layer). For binding compliance decisions, verify against the original Lampiran XIII."],
   z:["TCLP = 浸出毒性试验；TK（Total Konsentrasi）= 总浓度。A/B/C 类别决定污染土壤的处置方式：超过 A 值按第 1 类 B3 危险废物处置，介于 A 与 B 之间按第 2 类，低于 C 值可按未污染土壤管理。",
      "本表列出<strong>强制性无机</strong>参数。阴离子、有机物、农药及附加参数在原文件中采用相同结构。",
      "数值转录自官方 PDF（OCR 生成的文本层）。用于具有约束力的合规判定时，请核对附件 XIII 原件。"]
  }
},

// ── Lampiran XIV — registered non-B3 waste ──
nonb3:{
  code:"PP 22/2021 Lampiran XIV",
  title:{i:"Limbah Non-B3 Terdaftar",e:"Registered Non-B3 (Non-Hazardous) Waste",z:"已登记的非 B3（非危险）废物"},
  cols:{i:["No","Kode Limbah","Jenis Limbah Non-B3","Sumber Limbah"],
        e:["No","Waste Code","Non-B3 Waste Type","Waste Source"],
        z:["序号","废物代码","非 B3 废物类型","废物来源"]},
  rows:[
   {n:"1",p:{i:"N101",e:"N101",z:"N101"},u:"Slag Besi/Baja (Steel Slag)|Iron/Steel Slag|钢渣",v:["Proses peleburan bijih dan/atau logam besi dan baja|Smelting of iron ore and/or ferrous metal and steel|铁矿石和/或黑色金属与钢的冶炼过程"],k:{i:"",e:"",z:""}},
   {n:"2",p:{i:"N102",e:"N102",z:"N102"},u:"Slag Nikel (Nickel Slag)|Nickel Slag|镍渣",v:["Proses peleburan bijih nikel|Smelting of nickel ore|镍矿石冶炼过程"],k:{i:"",e:"",z:""}},
   {n:"3",p:{i:"N103",e:"N103",z:"N103"},u:"Mill scale|Mill scale|氧化铁皮",v:["Peleburan bijih dan/atau logam besi dan baja dengan teknologi selain induction furnace/kupola|Smelting of iron ore and/or ferrous metal and steel using technology other than induction furnace/cupola|采用感应炉/冲天炉以外技术的铁矿石与钢冶炼"],k:{i:"",e:"",z:""}},
   {n:"4",p:{i:"N104",e:"N104",z:"N104"},u:"Debu EAF|EAF dust|电弧炉粉尘",v:["Peleburan bijih dan/atau logam besi dan baja dengan teknologi electric arc furnace (EAF)|Smelting of iron ore and/or ferrous metal and steel using electric arc furnace (EAF)|采用电弧炉 (EAF) 技术的铁矿石与钢冶炼"],k:{i:"",e:"",z:""}},
   {n:"5",p:{i:"N105",e:"N105",z:"N105"},u:"PS ball|PS ball|PS 球",v:["Peleburan bijih dan/atau logam besi dan baja dengan teknologi selain induction furnace atau kupola|Smelting of iron ore and/or ferrous metal and steel using technology other than induction furnace or cupola|采用感应炉或冲天炉以外技术的铁矿石与钢冶炼"],k:{i:"",e:"",z:""}},
   {n:"6",p:{i:"N106",e:"N106",z:"N106"},u:"Fly ash|Fly ash|粉煤灰",v:["Pembakaran batubara pada PLTU atau kegiatan lain dengan teknologi selain stoker boiler dan/atau tungku industri|Coal combustion at steam power plants or other activities using technology other than stoker boilers and/or industrial furnaces|燃煤电厂或其他采用非链条炉排锅炉/工业炉技术的活动的燃煤过程"],k:{i:"",e:"",z:""}},
   {n:"7",p:{i:"N107",e:"N107",z:"N107"},u:"Bottom ash|Bottom ash|炉底渣",v:["Pembakaran batubara pada PLTU atau kegiatan lain dengan teknologi selain stoker boiler dan/atau tungku industri|Coal combustion at steam power plants or other activities using technology other than stoker boilers and/or industrial furnaces|燃煤电厂或其他采用非链条炉排锅炉/工业炉技术的活动的燃煤过程"],k:{i:"",e:"",z:""}},
   {n:"8",p:{i:"N108",e:"N108",z:"N108"},u:"Spent bleaching earth (SBE Ekstraksi)|Spent bleaching earth (extracted SBE)|废白土（萃取后 SBE）",v:["Industri oleochemical dan/atau pengolahan minyak hewani atau nabati yang menghasilkan SBE hasil ekstraksi|Oleochemical industry and/or animal or vegetable oil processing producing extracted SBE|油脂化学工业和/或动植物油加工产生的萃取废白土"],k:{i:"",e:"",z:""}},
   {n:"9",p:{i:"N109",e:"N109",z:"N109"},u:"Limbah non-B3 lain terdaftar|Other registered non-B3 waste|其他已登记非 B3 废物",v:["Sesuai daftar pada Lampiran XIV dokumen asli|Per the list in Lampiran XIV of the source document|按原文件附件 XIV 清单"],k:{i:"",e:"",z:""}}
  ],
  foot:{
   i:["Limbah non-B3 terdaftar dikelola dengan <strong>Rincian Teknis</strong> yang dimuat dalam Persetujuan Lingkungan, bukan dengan Persetujuan Teknis (PERTEK) penuh sebagaimana Limbah B3.",
      "Fly ash dan bottom ash (FABA) dari PLTU dikeluarkan dari daftar Limbah B3 melalui PP 22/2021 dan masuk kategori Limbah non-B3 terdaftar — perubahan yang berdampak besar pada proyek ketenagalistrikan dan pemanfaatan FABA sebagai bahan konstruksi.",
      "Kolom sumber diringkas dari uraian pada dokumen asli."],
   e:["Registered non-B3 waste is managed through a <strong>Rincian Teknis</strong> recorded in the Environmental Approval, rather than the full Persetujuan Teknis (PERTEK) required for B3 waste.",
      "Fly ash and bottom ash (FABA) from coal power plants were removed from the B3 list by PP 22/2021 and placed in the registered non-B3 category — a change with major consequences for power projects and for reusing FABA as a construction material.",
      "The source column is condensed from the description in the original document."],
   z:["已登记的非 B3 废物通过纳入环境批准的<strong>技术细则（Rincian Teknis）</strong>管理，而非 B3 危险废物所需的完整技术批准（PERTEK）。",
      "燃煤电厂的粉煤灰与炉底渣（FABA）经 PP 22/2021 从 B3 危险废物清单中移出，列为已登记非 B3 废物 — 该变更对电力项目及 FABA 作为建材再利用影响重大。",
      "来源栏为原文件描述的浓缩表述。"]
  }
}

};
