// ================================================================
// Engineering Standards Dictionary — Design Procedure Guidelines
// Step-by-step design workflows per element, keyed by answer-module
// key. Each step cites the governing clause (SNI / ACI-AISC-ASCE /
// GB). Rendered as a collapsible card after the answer module.
// ================================================================
window.PROCEDURES={

seismic:{icon:"🌍",
 en:{title:"Seismic Design Procedure — Equivalent Lateral Force",
   standard:"SNI 1726:2019 (≈ ASCE 7-16/22) · GB 50011-2010",
   steps:[
    {t:"Determine Risk Category (I–IV) from building use/occupancy, and the Importance Factor Ie",ref:"SNI 1726 §4.1.2, Tabel 1 & 2"},
    {t:"Classify the Site Class (SA–SF) from Vs30, N-SPT or Su (borehole ≥ 30 m)",ref:"SNI 1726 §5.3, Tabel 3"},
    {t:"Obtain mapped spectral accelerations Ss (0.2 s) and S1 (1.0 s) for the site coordinates (hazard map / RSA portal)",ref:"SNI 1726 §6.1.1"},
    {t:"Read site coefficients Fa, Fv; compute SMS = Fa·Ss and SM1 = Fv·S1 (MCER)",ref:"SNI 1726 §6.2, Tabel 6 & 7"},
    {t:"Design spectral accelerations: SDS = ⅔·SMS, SD1 = ⅔·SM1",ref:"SNI 1726 §6.3"},
    {t:"Build the design response spectrum: T0 = 0.2·SD1/SDS, Ts = SD1/SDS, then ascending / plateau / SD1/T / SD1·TL/T² branches",ref:"SNI 1726 §6.4"},
    {t:"Determine the Seismic Design Category (SDC A–F) — the more severe of the SDS- and SD1-based categories",ref:"SNI 1726 §6.5, Tabel 8 & 9"},
    {t:"Select the seismic force-resisting system → R, Ω₀, Cd and verify height limit for the SDC",ref:"SNI 1726 §7.2, Tabel 12"},
    {t:"Approximate period Ta = Ct·hn^x; seismic coefficient Cs = SDS/(R/Ie) (within limits); base shear V = Cs·W",ref:"SNI 1726 §7.8.1–7.8.2"},
    {t:"Distribute V vertically (Fx = Cvx·V); compute storey shears; run the structural analysis",ref:"SNI 1726 §7.8.3–7.8.4"},
    {t:"Check storey drift Δ ≤ Δa, redundancy ρ, P-delta, torsion; include vertical seismic Ev = 0.2·SDS·D in load combinations",ref:"SNI 1726 §7.8.6–7.8.7, §7.3–7.4, Tabel 20"},
    {t:"Detail the members & connections to the ductility requirements of the selected system",ref:"SNI 2847 Ch.18 / SNI 1729 seismic"}],
   alt:"🇺🇸 ASCE 7-22 follows the identical sequence (§11–12; Cs, R, Ω₀, Cd from Table 12.2-1). 🇨🇳 GB 50011 differs: classify 抗震设防烈度 & 设计地震分组 → site class I–IV & Tg → spectrum α(T) with αmax → base shear FEk = α1·Geq (bottom-shear method) or modal analysis → internal-force adjustment by seismic grade (一~四级, 强柱弱梁/强剪弱弯) → check elastic drift (frequent EQ) & elasto-plastic drift (rare EQ)."},
 zh:{title:"抗震设计流程 — 等效侧力法",
   standard:"SNI 1726:2019（≈ ASCE 7-16/22） · GB 50011-2010",
   steps:[
    {t:"按建筑使用功能确定风险类别（I–IV）及重要性系数 Ie",ref:"SNI 1726 §4.1.2、表 1 与 2"},
    {t:"由 Vs30、N-SPT 或 Su 确定场地类别（SA–SF）（钻孔 ≥ 30 m）",ref:"SNI 1726 §5.3、表 3"},
    {t:"按场地坐标获取地震区划谱加速度 Ss（0.2 s）与 S1（1.0 s）（区划图 / RSA 门户）",ref:"SNI 1726 §6.1.1"},
    {t:"查场地系数 Fa、Fv；计算 SMS = Fa·Ss、SM1 = Fv·S1（MCER）",ref:"SNI 1726 §6.2、表 6 与 7"},
    {t:"设计谱加速度：SDS = ⅔·SMS、SD1 = ⅔·SM1",ref:"SNI 1726 §6.3"},
    {t:"绘制设计反应谱：T0 = 0.2·SD1/SDS、Ts = SD1/SDS，分上升段/平台段/SD1/T/SD1·TL/T² 各段",ref:"SNI 1726 §6.4"},
    {t:"确定抗震设计类别（SDC A–F）— 取基于 SDS 与 SD1 两者中较严者",ref:"SNI 1726 §6.5、表 8 与 9"},
    {t:"选择抗震侧力体系 → R、Ω₀、Cd，并核对该 SDC 的高度限值",ref:"SNI 1726 §7.2、表 12"},
    {t:"近似周期 Ta = Ct·hn^x；地震系数 Cs = SDS/(R/Ie)（取限值内）；基底剪力 V = Cs·W",ref:"SNI 1726 §7.8.1–7.8.2"},
    {t:"沿竖向分配 V（Fx = Cvx·V）；计算楼层剪力；进行结构分析",ref:"SNI 1726 §7.8.3–7.8.4"},
    {t:"验算层间位移 Δ ≤ Δa、冗余系数 ρ、P-Δ 效应、扭转；荷载组合计入竖向地震 Ev = 0.2·SDS·D",ref:"SNI 1726 §7.8.6–7.8.7、§7.3–7.4、表 20"},
    {t:"按所选体系的延性要求对构件与节点进行抗震构造",ref:"SNI 2847 第18章 / SNI 1729 抗震"}],
   alt:"🇺🇸 ASCE 7-22 流程相同（§11–12；Cs、R、Ω₀、Cd 取自表 12.2-1）。🇨🇳 GB 50011 不同：确定抗震设防烈度与设计地震分组 → 场地类别 I–IV 与 Tg → 反应谱 α(T)（αmax）→ 底部剪力 FEk = α1·Geq（底部剪力法）或振型分解 → 按抗震等级（一~四级，强柱弱梁/强剪弱弯）内力调整 → 校核多遇地震弹性位移与罕遇地震弹塑性位移。"}},

concrete:{icon:"🏗",
 en:{title:"Reinforced Concrete Beam Design Procedure (Flexure + Shear)",
   standard:"SNI 2847:2019 (≈ ACI 318-19) · GB 50010-2010",
   steps:[
    {t:"Establish factored design moment Mu and shear Vu from the governing load combinations",ref:"SNI 1727 §2.3 / SNI 2847 §5.3"},
    {t:"Choose fc′ and fy; set section b, h and effective depth d (≥ minimum thickness to skip deflection check)",ref:"SNI 2847 §9.3, §19.2, §20"},
    {t:"Required flexural resistance Rn = Mu/(φ·b·d²) with φ = 0.90 (tension-controlled)",ref:"SNI 2847 §21.2, §22.2"},
    {t:"Reinforcement ratio ρ = (0.85fc′/fy)·[1 − √(1 − 2Rn/(0.85fc′))]",ref:"SNI 2847 §22.2"},
    {t:"Check ρmin ≤ ρ ≤ ρmax (εt ≥ 0.005); As = ρ·b·d; select bars, verify spacing & cover",ref:"SNI 2847 §9.6.1, §25.2, Tabel 20.6.1.3"},
    {t:"Confirm φMn ≥ Mu",ref:"SNI 2847 §9.5"},
    {t:"Shear: Vc = 0.17·λ·√fc′·bw·d; if Vu > φVc provide stirrups Av/s ≥ (Vu/φ − Vc)/(fyt·d); check spacing ≤ d/2",ref:"SNI 2847 §22.5, §9.7.6"},
    {t:"Detailing: development length, lap splices, bar cut-offs, deflection & crack control",ref:"SNI 2847 §25.4–25.5, §24"}],
   seismic:[
    {t:"Seismic load effect enters the combinations directly: use 1.2D + Ev + Eh + L and 0.9D − Ev + Eh, with horizontal Eh = ρ·QE (redundancy ρ = 1.0 or 1.3) and vertical Ev = 0.2·SDS·D",ref:"SNI 1727 §2.3.6 / SNI 1726 §7.3–7.4"},
    {t:"Pick the concrete seismic system from the SDC: SDC A–B ordinary, C intermediate (SRPMM), D–F Special Moment Frame (SRPMK) — this sets R, Ω₀, Cd used to scale QE",ref:"SNI 1726 Tabel 12 / SNI 2847 §18.2"},
    {t:"Beam flexure ρ ≤ 0.025 with ≥2 continuous top & bottom bars; positive moment at the joint face ≥ ½ of the negative moment (SRPMK ductility)",ref:"SNI 2847 §18.6.3"},
    {t:"Strong-column–weak-beam: at every joint ΣMnc ≥ 1.2·ΣMnb so hinges form in beams, not columns",ref:"SNI 2847 §18.7.3"},
    {t:"Capacity-design shear: size beam/column transverse steel for the shear from probable moments Mpr (fs = 1.25·fy); take Vc = 0 in the hinge zone and use φ = 0.6 if this shear governs",ref:"SNI 2847 §18.6.5, §18.7.6, §21.2.4"},
    {t:"Confinement over Lo: hoop spacing ≤ min(d/4 or b/4, 6db, so); column Ash ≥ max[0.3(Ag/Ach−1)fc′/fyt, 0.09fc′/fyt]; joint shear Vn = (1.7/1.25/1.0)·√fc′·Aj",ref:"SNI 2847 §18.6.4, §18.7.5, §18.8.4"}],
   alt:"🇺🇸 ACI 318-19 is identical (SNI 2847 adopts it). 🇨🇳 GB 50010: factored M from 1.3G+1.5Q; flexure via αs = M/(α1·fc·b·h0²) → ξ = 1−√(1−2αs) → As = α1·fc·b·ξ·h0/fy; ρmin from 表8.5.1; shear V ≤ 0.7·ft·b·h0 + fyv·Asv·h0/s; importance factor γ0. Seismic: internal forces adjusted by 抗震等级 (一~四级) with 强柱弱梁/强剪弱弯, seismic combo 1.3(G+0.5Q)+1.4·γEh·Eh(+0.5·γEv·Ev), γRE = 0.75–0.85."},
 zh:{title:"钢筋混凝土梁设计流程（受弯 + 受剪）",
   standard:"SNI 2847:2019（≈ ACI 318-19） · GB 50010-2010",
   steps:[
    {t:"由控制荷载组合确定设计弯矩 Mu 与剪力 Vu",ref:"SNI 1727 §2.3 / SNI 2847 §5.3"},
    {t:"选定 fc′ 与 fy；确定截面 b、h 及有效高度 d（取 ≥ 最小高度以免算挠度）",ref:"SNI 2847 §9.3、§19.2、§20"},
    {t:"所需受弯抗力 Rn = Mu/(φ·b·d²)，φ = 0.90（受拉控制）",ref:"SNI 2847 §21.2、§22.2"},
    {t:"配筋率 ρ = (0.85fc′/fy)·[1 − √(1 − 2Rn/(0.85fc′))]",ref:"SNI 2847 §22.2"},
    {t:"校核 ρmin ≤ ρ ≤ ρmax（εt ≥ 0.005）；As = ρ·b·d；选筋并验算间距与保护层",ref:"SNI 2847 §9.6.1、§25.2、表20.6.1.3"},
    {t:"确认 φMn ≥ Mu",ref:"SNI 2847 §9.5"},
    {t:"受剪：Vc = 0.17·λ·√fc′·bw·d；Vu > φVc 时配箍 Av/s ≥ (Vu/φ − Vc)/(fyt·d)；间距 ≤ d/2",ref:"SNI 2847 §22.5、§9.7.6"},
    {t:"构造：锚固长度、搭接、钢筋截断、挠度与裂缝控制",ref:"SNI 2847 §25.4–25.5、§24"}],
   seismic:[
    {t:"地震作用直接进入组合：采用 1.2D + Ev + Eh + L 与 0.9D − Ev + Eh，水平 Eh = ρ·QE（冗余系数 ρ = 1.0 或 1.3）、竖向 Ev = 0.2·SDS·D",ref:"SNI 1727 §2.3.6 / SNI 1726 §7.3–7.4"},
    {t:"按 SDC 选择混凝土抗震体系：SDC A–B 普通、C 中等（SRPMM）、D–F 特殊抗弯框架（SRPMK）— 由此定 R、Ω₀、Cd 以缩放 QE",ref:"SNI 1726 表12 / SNI 2847 §18.2"},
    {t:"梁受弯 ρ ≤ 0.025，上下各 ≥2 根通长筋；节点面正弯矩 ≥ 负弯矩的 ½（SRPMK 延性）",ref:"SNI 2847 §18.6.3"},
    {t:"强柱弱梁：每个节点 ΣMnc ≥ 1.2·ΣMnb，使塑性铰出现在梁而非柱",ref:"SNI 2847 §18.7.3"},
    {t:"能力设计受剪：梁柱横向钢筋按概率弯矩 Mpr（fs = 1.25·fy）产生的剪力配置；铰区取 Vc = 0，该剪力控制时 φ = 0.6",ref:"SNI 2847 §18.6.5、§18.7.6、§21.2.4"},
    {t:"Lo 范围约束：箍筋间距 ≤ min(d/4 或 b/4, 6db, so)；柱 Ash ≥ max[0.3(Ag/Ach−1)fc′/fyt, 0.09fc′/fyt]；节点受剪 Vn = (1.7/1.25/1.0)·√fc′·Aj",ref:"SNI 2847 §18.6.4、§18.7.5、§18.8.4"}],
   alt:"🇺🇸 ACI 318-19 完全相同（SNI 2847 即采标）。🇨🇳 GB 50010：M 由 1.3G+1.5Q；受弯 αs = M/(α1·fc·b·h0²) → ξ = 1−√(1−2αs) → As = α1·fc·b·ξ·h0/fy；ρmin 见表8.5.1；受剪 V ≤ 0.7·ft·b·h0 + fyv·Asv·h0/s；重要性系数 γ0。抗震：内力按抗震等级（一~四级）以强柱弱梁/强剪弱弯调整，地震组合 1.3(G+0.5Q)+1.4·γEh·Eh(+0.5·γEv·Ev)，γRE = 0.75–0.85。"}},

steel:{icon:"🔩",
 en:{title:"Structural Steel Member Design Procedure (LRFD)",
   standard:"SNI 1729:2020 (≈ AISC 360-16/22) · GB 50017-2017",
   steps:[
    {t:"Determine required strengths Pu, Mu, Vu from factored LRFD load combinations",ref:"SNI 1727 §2.3 / AISC 360 §B3"},
    {t:"Select trial section & steel grade (Fy, Fu); establish unbraced lengths Lb, KL",ref:"AISC 360 §A3, Manual"},
    {t:"Classify the section (compact / non-compact / slender) for flange & web",ref:"AISC 360 Table B4.1"},
    {t:"Tension: φt·Pn = min(0.90·Fy·Ag , 0.75·Fu·Ae)",ref:"AISC 360 Ch.D"},
    {t:"Compression: φc = 0.90, Pn = Fcr·Ag with Fcr from λc = KL/r (flexural/torsional buckling)",ref:"AISC 360 Ch.E"},
    {t:"Flexure: φb = 0.90, Mn = least of yielding, lateral-torsional buckling, local buckling",ref:"AISC 360 Ch.F"},
    {t:"Shear: φv·Vn = (1.00 or 0.90)·0.6·Fy·Aw·Cv",ref:"AISC 360 Ch.G"},
    {t:"Combined axial + flexure interaction (H1-1a/b)",ref:"AISC 360 Ch.H"},
    {t:"Stability (direct analysis or effective length) and connection design",ref:"AISC 360 Ch.C & Ch.J"}],
   seismic:[
    {t:"Seismic combinations: 1.2D + Ev + Eh + L and 0.9D − Ev + Eh, with Eh = ρ·QE and Ev = 0.2·SDS·D — the same SNI 1726 parameters that drive concrete design",ref:"SNI 1727 §2.3.6 / SNI 1726 §7.3–7.4"},
    {t:"Select the steel seismic system → R, Ω₀, Cd: SMF/SRPMK R = 8, IMF R = 4.5, SCBF R = 6, EBF R = 8, OMF R = 3.5 (SDC A–C may use R = 3 without seismic detailing)",ref:"SNI 1726 Tabel 12 / AISC 341"},
    {t:"Overstrength load effect Emh = Ω₀·QE for force-controlled/brittle elements (columns, collectors, connections not part of the ductile mechanism): 1.2D + Ev + Ω₀·QE + L",ref:"SNI 1726 §7.4.3"},
    {t:"For SDC ≥ D apply AISC 341 ductile detailing: highly-ductile width-thickness limits λhd, protected zones, demand-critical welds, and the strong-column–weak-beam ratio ΣM*pc/ΣM*pb > 1.0 (SMF)",ref:"AISC 341 §D1, §E3 / SNI 7860"},
    {t:"Capacity-design connections & panel zone to the expected member strength Ry·Fy (Ry ≈ 1.1–1.5); braces in SCBF designed for expected buckling/yield",ref:"AISC 341 §A3.2, §F2"}],
   alt:"🇺🇸 AISC 360 is the parent of SNI 1729. 🇨🇳 GB 50017 uses design strength f = fy/γR (Q235 f≈215, Q355 f≈305 MPa); checks σ = N/An ≤ f, σ = M/(γx·Wnx) ≤ f, stability N/(φ·A) ≤ f and Mx/(φb·Wx) ≤ f, with stability factors φ/φb from Appendix tables; slenderness λ ≤ 150 (compression). Seismic per GB 50011: 抗震等级 (一~四级), 强柱弱梁 with column over-strength factor, seismic combo with γRE = 0.75–0.85."},
 zh:{title:"钢结构构件设计流程（LRFD）",
   standard:"SNI 1729:2020（≈ AISC 360-16/22） · GB 50017-2017",
   steps:[
    {t:"由 LRFD 荷载组合确定所需内力 Pu、Mu、Vu",ref:"SNI 1727 §2.3 / AISC 360 §B3"},
    {t:"选取试算截面与钢材牌号（Fy、Fu）；确定无支撑长度 Lb、KL",ref:"AISC 360 §A3、手册"},
    {t:"截面分类（厚实/非厚实/细长）— 翼缘与腹板",ref:"AISC 360 表B4.1"},
    {t:"受拉：φt·Pn = min(0.90·Fy·Ag , 0.75·Fu·Ae)",ref:"AISC 360 第D章"},
    {t:"受压：φc = 0.90，Pn = Fcr·Ag，Fcr 由 λc = KL/r（弯曲/扭转屈曲）",ref:"AISC 360 第E章"},
    {t:"受弯：φb = 0.90，Mn 取屈服、弯扭屈曲、局部屈曲最小值",ref:"AISC 360 第F章"},
    {t:"受剪：φv·Vn = (1.00 或 0.90)·0.6·Fy·Aw·Cv",ref:"AISC 360 第G章"},
    {t:"轴力+弯矩组合相关（H1-1a/b）",ref:"AISC 360 第H章"},
    {t:"稳定（直接分析或计算长度）与节点设计",ref:"AISC 360 第C章 与 第J章"}],
   seismic:[
    {t:"地震组合：1.2D + Ev + Eh + L 与 0.9D − Ev + Eh，Eh = ρ·QE、Ev = 0.2·SDS·D — 与混凝土设计相同的 SNI 1726 参数",ref:"SNI 1727 §2.3.6 / SNI 1726 §7.3–7.4"},
    {t:"选择钢结构抗震体系 → R、Ω₀、Cd：SMF/SRPMK R = 8、IMF R = 4.5、SCBF R = 6、EBF R = 8、OMF R = 3.5（SDC A–C 可取 R = 3 免抗震构造）",ref:"SNI 1726 表12 / AISC 341"},
    {t:"超强地震作用 Emh = Ω₀·QE 用于内力控制/脆性构件（柱、传力构件、非延性机制节点）：1.2D + Ev + Ω₀·QE + L",ref:"SNI 1726 §7.4.3"},
    {t:"SDC ≥ D 时按 AISC 341 延性构造：高延性宽厚比限值 λhd、保护区、需求关键焊缝、强柱弱梁比 ΣM*pc/ΣM*pb > 1.0（SMF）",ref:"AISC 341 §D1、§E3 / SNI 7860"},
    {t:"节点与节点域按预期构件强度 Ry·Fy（Ry ≈ 1.1–1.5）能力设计；SCBF 支撑按预期屈曲/屈服设计",ref:"AISC 341 §A3.2、§F2"}],
   alt:"🇺🇸 AISC 360 为 SNI 1729 的母规范。🇨🇳 GB 50017 用设计强度 f = fy/γR（Q235 f≈215、Q355 f≈305 MPa）；验算 σ = N/An ≤ f、σ = M/(γx·Wnx) ≤ f、稳定 N/(φ·A) ≤ f 与 Mx/(φb·Wx) ≤ f；受压长细比 λ ≤ 150。抗震按 GB 50011：抗震等级（一~四级）、强柱弱梁（柱超强系数）、地震组合 γRE = 0.75–0.85。"}},

geotechnical:{icon:"🏚",
 en:{title:"Foundation Design Procedure (Shallow & Deep)",
   standard:"SNI 8460:2017 · GB 50007-2011 / JGJ 94-2008 · ACI 543R-12",
   steps:[
    {t:"Site investigation: boreholes ≥ 6 m below footing base (≥ 30 m for seismic site class), SPT/CPT, groundwater",ref:"SNI 8460 §6"},
    {t:"Establish soil profile & parameters (c, φ, γ, N60, qc, Es, Su, GWT)",ref:"SNI 8460 §6–7"},
    {t:"Select foundation type by soil strength, load and settlement sensitivity (shallow vs deep)",ref:"SNI 8460 §7 & §9"},
    {t:"SHALLOW — ultimate bearing qu = c·Nc + q·Nq + 0.5·γ·B·Nγ; allowable qa = qu/FS (FS ≥ 3.0 static, 2.0 seismic)",ref:"SNI 8460 §7.4"},
    {t:"Size the footing so service pressure ≤ qa; check eccentricity (e ≤ B/6) and bearing under combined loads",ref:"SNI 8460 §7 / GB 50007 §5.2"},
    {t:"Settlement check: immediate + consolidation ≤ limits (total ≤ 50 mm, differential ≤ 25 mm)",ref:"SNI 8460 §8.6"},
    {t:"Structural design of footing: flexure, one-way & punching shear, reinforcement",ref:"SNI 2847 §13, §22.6"},
    {t:"DEEP — single-pile capacity Qu = Σ(fs·As) + qp·Ap; Qa = Qu/FS (2.0 with load test); group efficiency, negative friction, lateral, settlement",ref:"SNI 8460 §9 · JGJ 94 §5.3"},
    {t:"Pile detailing: spacing ≥ 3D, reinforcement ratio, cover 75 mm, cap design",ref:"JGJ 94 §3.3, §4.1 · ACI 543R"}],
   alt:"🇨🇳 GB 50007 uses the characteristic bearing value fa = fak + ηb·γ·(b−3) + ηd·γm·(d−0.5) and verifies pk ≤ fa, pkmax ≤ 1.2fa. 🇺🇸 practice: IBC presumptive values or geotechnical report; ACI 543R for concrete piles."},
 zh:{title:"地基基础设计流程（浅基础与深基础）",
   standard:"SNI 8460:2017 · GB 50007-2011 / JGJ 94-2008 · ACI 543R-12",
   steps:[
    {t:"场地勘察：钻孔至基底以下 ≥ 6 m（确定场地类别 ≥ 30 m），SPT/CPT，地下水",ref:"SNI 8460 §6"},
    {t:"确定土层剖面与参数（c、φ、γ、N60、qc、Es、Su、地下水位）",ref:"SNI 8460 §6–7"},
    {t:"按土的强度、荷载与沉降敏感性选择基础类型（浅基础 vs 深基础）",ref:"SNI 8460 §7 与 §9"},
    {t:"浅基础 — 极限承载力 qu = c·Nc + q·Nq + 0.5·γ·B·Nγ；容许 qa = qu/FS（静载 FS ≥ 3.0、地震 2.0）",ref:"SNI 8460 §7.4"},
    {t:"确定基础尺寸使工作压力 ≤ qa；验算偏心（e ≤ B/6）及组合荷载下承载",ref:"SNI 8460 §7 / GB 50007 §5.2"},
    {t:"沉降验算：瞬时 + 固结 ≤ 限值（总 ≤ 50 mm、差异 ≤ 25 mm）",ref:"SNI 8460 §8.6"},
    {t:"基础结构设计：受弯、单向剪与冲切、配筋",ref:"SNI 2847 §13、§22.6"},
    {t:"深基础 — 单桩承载力 Qu = Σ(fs·As) + qp·Ap；Qa = Qu/FS（有静载试验取 2.0）；群桩效率、负摩阻、水平、沉降",ref:"SNI 8460 §9 · JGJ 94 §5.3"},
    {t:"桩构造：桩距 ≥ 3D、配筋率、保护层 75 mm、承台设计",ref:"JGJ 94 §3.3、§4.1 · ACI 543R"}],
   alt:"🇨🇳 GB 50007 用承载力特征值 fa = fak + ηb·γ·(b−3) + ηd·γm·(d−0.5)，验算 pk ≤ fa、pkmax ≤ 1.2fa。🇺🇸 实践：IBC 经验值或岩土报告；混凝土桩按 ACI 543R。"}},

foundation_type:{ref:"geotechnical"},

design_loads:{icon:"📐",
 en:{title:"Design Load Determination Procedure",
   standard:"SNI 1727:2020 (≈ ASCE 7-16) · GB 50009-2012",
   steps:[
    {t:"Dead load D: sum self-weight of structure, finishes, fixed equipment, partitions (use material densities)",ref:"SNI 1727 §3"},
    {t:"Live load L: minimum uniform & concentrated values by occupancy; apply live-load reduction where allowed",ref:"SNI 1727 §4, Tabel 4.3-1"},
    {t:"Roof live Lr, rain R, and (where applicable) snow loads",ref:"SNI 1727 §4.8, Ch.8"},
    {t:"Wind W: see the Wind Load procedure (qz, G, Cp)",ref:"SNI 1727 §26–31"},
    {t:"Seismic E: see the Seismic Design procedure (V = Cs·W)",ref:"SNI 1726 §7"},
    {t:"Combine using LRFD/ultimate combinations (1.2D+1.6L, 1.2D+1.0W+L, 1.2D+Ev+Eh+L, 0.9D±…)",ref:"SNI 1727 §2.3"},
    {t:"Check serviceability combinations (deflection, vibration, drift)",ref:"SNI 1727 §2.4, App.C"}],
   seismic:[
    {t:"Seismic load effect E = Eh ± Ev: horizontal Eh = ρ·QE (redundancy ρ = 1.0 or 1.3 by SDC/plan) and vertical Ev = 0.2·SDS·D added to gravity",ref:"SNI 1726 §7.4.1–7.4.2"},
    {t:"Strength combinations with earthquake: (1.2 + 0.2SDS)D + ρQE + L and (0.9 − 0.2SDS)D + ρQE",ref:"SNI 1727 §2.3.6 / SNI 1726 §7.4"},
    {t:"Overstrength combinations (Em = Ω₀·QE) where required for non-ductile/force-controlled elements: (1.2 + 0.2SDS)D + Ω₀·QE + L and (0.9 − 0.2SDS)D + Ω₀·QE",ref:"SNI 1726 §7.4.3, Tabel 12"},
    {t:"Importance factor Ie by Risk Category (I→1.0, II→1.0, III→1.25, IV→1.50) scales the seismic base shear V = Cs·W where Cs = SDS/(R/Ie)",ref:"SNI 1726 Tabel 2, §7.8.1"},
    {t:"Vertical distribution & storey drift: Fx = Cvx·V; check Δ ≤ Δa (drift limit by Risk Category) and P-delta",ref:"SNI 1726 §7.8.3, §7.12, Tabel 20"}],
   alt:"🇨🇳 GB 50009/GB 55001: characteristic values × γ (permanent 1.3, variable 1.5) with combination-value coefficients ψc; quasi-permanent & frequent combinations for serviceability. Seismic (GB 50011): S = γG·SGE + γEh·SEhk + γEv·SEvk + ψw·γw·Swk, with γG=1.2 (1.0 favourable), γEh=γEv=1.3, and capacity design via 抗震等级."},
 zh:{title:"设计荷载取值流程",
   standard:"SNI 1727:2020（≈ ASCE 7-16） · GB 50009-2012",
   steps:[
    {t:"恒载 D：结构自重 + 面层 + 固定设备 + 隔墙（按材料密度）",ref:"SNI 1727 §3"},
    {t:"活载 L：按使用功能取最小均布与集中值；满足条件时折减",ref:"SNI 1727 §4、表4.3-1"},
    {t:"屋面活载 Lr、雨载 R 及（如适用）雪载",ref:"SNI 1727 §4.8、第8章"},
    {t:"风载 W：见风荷载流程（qz、G、Cp）",ref:"SNI 1727 §26–31"},
    {t:"地震 E：见抗震设计流程（V = Cs·W）",ref:"SNI 1726 §7"},
    {t:"按承载能力组合（1.2D+1.6L、1.2D+1.0W+L、1.2D+Ev+Eh+L、0.9D±…）",ref:"SNI 1727 §2.3"},
    {t:"校核正常使用组合（挠度、振动、位移）",ref:"SNI 1727 §2.4、附录C"}],
   seismic:[
    {t:"地震作用 E = Eh ± Ev：水平 Eh = ρ·QE（冗余系数 ρ = 1.0 或 1.3，按 SDC/平面）、竖向 Ev = 0.2·SDS·D 叠加于重力",ref:"SNI 1726 §7.4.1–7.4.2"},
    {t:"含地震的承载力组合：(1.2 + 0.2SDS)D + ρQE + L 与 (0.9 − 0.2SDS)D + ρQE",ref:"SNI 1727 §2.3.6 / SNI 1726 §7.4"},
    {t:"超强组合（Em = Ω₀·QE）用于非延性/内力控制构件：(1.2 + 0.2SDS)D + Ω₀·QE + L 与 (0.9 − 0.2SDS)D + Ω₀·QE",ref:"SNI 1726 §7.4.3、表12"},
    {t:"重要性系数 Ie 按风险类别（I→1.0、II→1.0、III→1.25、IV→1.50）缩放基底剪力 V = Cs·W，其中 Cs = SDS/(R/Ie)",ref:"SNI 1726 表2、§7.8.1"},
    {t:"竖向分配与层间位移：Fx = Cvx·V；校核 Δ ≤ Δa（按风险类别的位移限值）与 P-Δ",ref:"SNI 1726 §7.8.3、§7.12、表20"}],
   alt:"🇨🇳 GB 50009/GB 55001：标准值 × 分项系数（恒 1.3、活 1.5）配组合值系数 ψc；正常使用按准永久/频遇组合。抗震（GB 50011）：S = γG·SGE + γEh·SEhk + γEv·SEvk + ψw·γw·Swk，γG=1.2（有利 1.0）、γEh=γEv=1.3，并按抗震等级能力设计。"}},

wind:{icon:"🌬",
 en:{title:"Wind Load Procedure — Directional (MWFRS)",
   standard:"SNI 1727:2020 (≈ ASCE 7-16) · GB 50009-2012",
   steps:[
    {t:"Risk Category → basic wind speed V (3-s gust) from the map / authority",ref:"SNI 1727 §26.5"},
    {t:"Exposure Category B/C/D from terrain; directionality Kd, ground elevation Ke",ref:"SNI 1727 §26.7, §26.6"},
    {t:"Topographic factor Kzt = (1+K1·K2·K3)² for hills/escarpments (else 1.0)",ref:"SNI 1727 §26.8"},
    {t:"Velocity pressure qz = 0.613·Kz·Kzt·Kd·Ke·V² (N/m²)",ref:"SNI 1727 §26.10"},
    {t:"Gust-effect factor G = 0.85 (rigid) or Gf computed for flexible structures (n1 < 1 Hz)",ref:"SNI 1727 §26.11"},
    {t:"Enclosure classification → internal pressure coefficient GCpi",ref:"SNI 1727 §26.12–26.13"},
    {t:"External pressure coefficients Cp (walls/roof) from figures",ref:"SNI 1727 §27.3, Fig 27.3"},
    {t:"Design pressure p = q·G·Cp − qi·(GCpi) for MWFRS; (GCp) method for Components & Cladding",ref:"SNI 1727 §27.4, Ch.30"},
    {t:"Apply to the structure; check overturning, sliding, uplift",ref:"SNI 1727 §27.4 / SNI 1726 §12"}],
   alt:"🇨🇳 GB 50009: wk = βz·μs·μz·w0, with basic wind pressure w0 (50-yr), exposure roughness A–D giving μz, shape factor μs, and gust/vibration factor βz; w0 ≥ 0.30 kN/m²."},
 zh:{title:"风荷载流程 — 方向法（主要抗风体系）",
   standard:"SNI 1727:2020（≈ ASCE 7-16） · GB 50009-2012",
   steps:[
    {t:"风险类别 → 基本风速 V（3 秒阵风，区划图/主管部门）",ref:"SNI 1727 §26.5"},
    {t:"按地貌确定暴露类别 B/C/D；方向性系数 Kd、地面高程 Ke",ref:"SNI 1727 §26.7、§26.6"},
    {t:"地形系数 Kzt = (1+K1·K2·K3)²（山丘/陡坎，否则取 1.0）",ref:"SNI 1727 §26.8"},
    {t:"速度压 qz = 0.613·Kz·Kzt·Kd·Ke·V²（N/m²）",ref:"SNI 1727 §26.10"},
    {t:"阵风效应系数 G = 0.85（刚性）或柔性结构计算 Gf（n1 < 1 Hz）",ref:"SNI 1727 §26.11"},
    {t:"封闭分类 → 内压系数 GCpi",ref:"SNI 1727 §26.12–26.13"},
    {t:"外压系数 Cp（墙/屋面，查图）",ref:"SNI 1727 §27.3、图27.3"},
    {t:"设计风压 p = q·G·Cp − qi·(GCpi)（主体）；围护构件用 (GCp) 法",ref:"SNI 1727 §27.4、第30章"},
    {t:"作用于结构；验算倾覆、滑移、上拔",ref:"SNI 1727 §27.4 / SNI 1726 §12"}],
   alt:"🇨🇳 GB 50009：wk = βz·μs·μz·w0；基本风压 w0（50 年）、地面粗糙度 A–D 给出 μz、体型系数 μs、风振系数 βz；w0 ≥ 0.30 kN/m²。"}},

purlin:{icon:"🏠",
 en:{title:"Cold-Formed Purlin / Girt Design Procedure",
   standard:"SNI 7971:2013 (≈ AISI S100) · GB 51022-2015 / GB 50018",
   steps:[
    {t:"Loads: dead (sheet+purlin) + roof live OR wind — check wind UPLIFT as a separate, often governing case",ref:"SNI 1727 / SNI 7971 §1"},
    {t:"Select section (C/Z), depth, thickness, spacing, span and lateral restraint (sheeting, sag rods)",ref:"SNI 7971 §1.5"},
    {t:"Compute the effective section (local & distortional buckling) — effective-width or Direct Strength Method",ref:"SNI 7971 §2 / AISI S100 App.1"},
    {t:"Flexural capacity φb·Mn including lateral-torsional buckling; under uplift the free flange is unbraced (R-factor method)",ref:"SNI 7971 §3.3, §3.5"},
    {t:"Shear and web crippling at supports/cleats",ref:"SNI 7971 §3.3.4"},
    {t:"Combined bending + shear at laps and supports",ref:"SNI 7971 §3.3.5"},
    {t:"Deflection check: ≤ L/150 (sheet roof) to L/240 (with ceiling)",ref:"GB 51022 App.A / IBC Table 1604.3"},
    {t:"Connections: screws to sheeting, M12 bolts at cleats, sag rods, lap length ≥ 10% span (continuous Z)",ref:"SNI 7971 §5 / GB 51022 §10"}],
   alt:"🇺🇸 AISI S100 (= SNI 7971) — ASD or LRFD with effective width / DSM. 🇨🇳 GB 51022 / GB 50018: portal-frame purlins with γ-factored loads, effective section, stress check σ ≤ f, deflection L/150–L/240, drift h/60."},
 zh:{title:"冷弯檩条 / 墙梁设计流程",
   standard:"SNI 7971:2013（≈ AISI S100） · GB 51022-2015 / GB 50018",
   steps:[
    {t:"荷载：恒载（板+檩）+ 屋面活载 或 风载 — 单独验算风吸力（常起控制作用）",ref:"SNI 1727 / SNI 7971 §1"},
    {t:"选择截面（C/Z）、高度、厚度、间距、跨度及侧向支撑（板、拉条）",ref:"SNI 7971 §1.5"},
    {t:"计算有效截面（局部与畸变屈曲）— 有效宽度法或直接强度法",ref:"SNI 7971 §2 / AISI S100 附录1"},
    {t:"受弯承载力 φb·Mn（含弯扭屈曲）；风吸力下自由翼缘无支撑（R 系数法）",ref:"SNI 7971 §3.3、§3.5"},
    {t:"支座/檩托处受剪与腹板压跛",ref:"SNI 7971 §3.3.4"},
    {t:"搭接与支座处弯剪组合",ref:"SNI 7971 §3.3.5"},
    {t:"挠度验算：≤ L/150（压型板屋面）至 L/240（有吊顶）",ref:"GB 51022 附录A / IBC 表1604.3"},
    {t:"连接：自攻钉连板、檩托 M12 螺栓、拉条、连续 Z 搭接长 ≥ 跨度 10%",ref:"SNI 7971 §5 / GB 51022 §10"}],
   alt:"🇺🇸 AISI S100（= SNI 7971）— ASD 或 LRFD，有效宽度/DSM。🇨🇳 GB 51022 / GB 50018：门式刚架檩条，分项荷载、有效截面、应力 σ ≤ f、挠度 L/150–L/240、位移 h/60。"}},

environmental:{icon:"🌿",
 en:{title:"Environmental Approval & Compliance Procedure (PP 22/2021)",
   standard:"PP 22/2021 · UU 32/2009 jo. UU 11/2020 · Permen PUPR 10/2021 (RKPPL) · IFC EHS Guidelines",
   steps:[
    {t:"Screen the activity against the wajib-AMDAL criteria to determine the approval tier: AMDAL (important impact), UKL-UPL (no important impact but managed), or SPPL (low impact)",ref:"PP 22/2021 — Persetujuan Lingkungan"},
    {t:"Identify the receiving environment and its designated status: the water-body class (Kelas I–IV) for any river or lake, the sea-water designation (Pelabuhan / Wisata Bahari / Biota Laut) for coastal works, and the ambient air baseline",ref:"PP 22/2021 Lampiran VI & VIII"},
    {t:"Establish the environmental baseline (rona lingkungan awal) by measurement — water, air, noise — recorded by location/STA with photographs, so post-construction compliance can be demonstrated against a defensible starting point",ref:"Permen PUPR 10/2021 Lampiran G"},
    {t:"For AMDAL: prepare the Formulir Kerangka Acuan → ANDAL → RKL-RPL, then submit for the feasibility test by the Tim Uji Kelayakan Lingkungan Hidup (TUK) to obtain the Persetujuan Kelayakan Lingkungan Hidup",ref:"PP 22/2021 — AMDAL"},
    {t:"For UKL-UPL: prepare the standard form and obtain the Persetujuan Pernyataan Kesanggupan Pengelolaan Lingkungan Hidup (PKPLH); for SPPL simply register the statement letter",ref:"PP 22/2021 — UKL-UPL / SPPL"},
    {t:"Obtain the Persetujuan Teknis (PERTEK) for each regulated stream: wastewater discharge, air emissions, B3 hazardous-waste management and/or disposal to sea — a Rincian Teknis suffices for non-hazardous waste",ref:"PP 22/2021 — Persetujuan Teknis"},
    {t:"Design discharge and emission controls so the receiving environment stays within its class limits — check effluent against the river/lake table for the assigned class, and stack/fugitive emissions against the ambient air standard",ref:"Lampiran VI & VII (tables in the parameters below)"},
    {t:"Secure the Persetujuan Lingkungan before the Perizinan Berusaha — the environmental approval is a prerequisite for the business/operating licence, not a parallel workstream",ref:"PP 22/2021 jo. UU 11/2020"},
    {t:"Carry the RKL-RPL or UKL-UPL commitments into the construction documents: the SMKK RKPPL must accommodate and elaborate every clause, and the RMLLP must cover traffic-related impacts",ref:"Permen PUPR 10/2021 Lampiran G & H"},
    {t:"Monitor during construction and operation at the frequency set in the approval — sample water, air and noise against the Lampiran VI/VII/VIII limits, log results, and report periodically to the issuing authority",ref:"PP 22/2021 — RKL-RPL monitoring"},
    {t:"Verify operational compliance and obtain the SLO (Surat Kelayakan Operasional) confirming the PERTEK conditions are met; maintain the evidence file for inspection and audit",ref:"PP 22/2021 — SLO"}],
   alt:"🇺🇸 United States: NEPA Environmental Assessment / Environmental Impact Statement, with NPDES permits for discharge (CWA) and Title V / NSR permits for emissions (CAA); construction stormwater under a CGP with a SWPPP. 🇨🇳 China: 环境影响评价 (EIA) report/form/registration by impact tier under 环评法, approval by the ecology & environment bureau, 排污许可证 (pollutant discharge permit), and 三同时 — pollution-control facilities designed, built and commissioned together with the main works; ambient standards GB 3095-2012 (air) and GB 3838-2002 (surface water)."},
 zh:{title:"环境审批与合规流程（PP 22/2021）",
   standard:"PP 22/2021 · UU 32/2009 与 UU 11/2020 · 部长条例 PUPR 10/2021（RKPPL） · IFC EHS 导则",
   steps:[
    {t:"对照强制 AMDAL 判定标准筛查项目，确定审批层级：AMDAL（有重大影响）、UKL-UPL（无重大影响但需管理）或 SPPL（影响轻微）",ref:"PP 22/2021 — 环境批准"},
    {t:"识别受纳环境及其功能定位：河流/湖泊的水体类别（I–IV 类）、涉海工程的海水功能区（港口/海洋旅游/海洋生物）以及环境空气本底",ref:"PP 22/2021 附件 VI 与 VIII"},
    {t:"通过实测建立环境本底（rona lingkungan awal）— 水、气、噪声 — 按位置/桩号记录并附照片，以便日后以可靠基准论证达标情况",ref:"部长条例 PUPR 10/2021 附件 G"},
    {t:"AMDAL 路径：编制《工作大纲表》→《环境影响分析 ANDAL》→《环境管理与监测计划 RKL-RPL》，提交环境可行性审查组（TUK）审查，取得《环境可行性批准》",ref:"PP 22/2021 — AMDAL"},
    {t:"UKL-UPL 路径：填报标准表格并取得《环境管理承诺声明批准（PKPLH）》；SPPL 仅需登记承诺函",ref:"PP 22/2021 — UKL-UPL / SPPL"},
    {t:"就各受控排放取得技术批准（PERTEK）：废水排放、大气排放、B3 危险废物管理和/或向海排放 — 一般固废提交《技术细则》即可",ref:"PP 22/2021 — 技术批准"},
    {t:"设计排放与治理措施，确保受纳环境维持在其类别限值内 — 废水对照所定类别的河流/湖泊限值，有组织与无组织排放对照环境空气标准",ref:"附件 VI 与 VII（见下方参数表）"},
    {t:"在取得营业许可（Perizinan Berusaha）之前先取得环境批准 — 环境批准是营业/运营许可的前置条件，而非并行事项",ref:"PP 22/2021 与 UU 11/2020"},
    {t:"将 RKL-RPL 或 UKL-UPL 承诺纳入施工文件：SMKK 的 RKPPL 必须承接并细化每一条款，RMLLP 须涵盖交通相关影响",ref:"部长条例 PUPR 10/2021 附件 G 与 H"},
    {t:"施工与运营期按批准文件规定的频次开展监测 — 对照附件 VI/VII/VIII 限值采样检测水、气、噪声，记录结果并定期向审批机关报告",ref:"PP 22/2021 — RKL-RPL 监测"},
    {t:"核验运营合规性并取得《运营合格证（SLO）》确认 PERTEK 条件已满足；建立并保存备查与审核的证据档案",ref:"PP 22/2021 — SLO"}],
   alt:"🇺🇸 美国：依 NEPA 编制环境评价（EA）/环境影响报告书（EIS）；排放依《清洁水法》申领 NPDES 许可，大气依《清洁空气法》申领 Title V / NSR 许可；施工期雨水按 CGP 并编制 SWPPP。🇨🇳 中国：依《环评法》按影响程度分别编制环境影响报告书/报告表/登记表，报生态环境主管部门审批，申领排污许可证，并执行\"三同时\"— 污染防治设施与主体工程同时设计、同时施工、同时投产；环境质量标准为 GB 3095-2012（空气）与 GB 3838-2002（地表水）。"},
 idn:{title:"Prosedur Persetujuan dan Kepatuhan Lingkungan (PP 22/2021)",
   standard:"PP 22/2021 · UU 32/2009 jo. UU 11/2020 · Permen PUPR 10/2021 (RKPPL) · Panduan EHS IFC",
   steps:[
    {t:"Saring kegiatan terhadap kriteria wajib AMDAL untuk menentukan jenjang persetujuan: AMDAL (berdampak penting), UKL-UPL (tidak berdampak penting namun dikelola), atau SPPL (dampak kecil)",ref:"PP 22/2021 — Persetujuan Lingkungan"},
    {t:"Identifikasi lingkungan penerima dan status peruntukannya: kelas badan air (Kelas I–IV) untuk sungai atau danau, peruntukan air laut (Pelabuhan / Wisata Bahari / Biota Laut) untuk pekerjaan pesisir, serta rona awal udara ambien",ref:"PP 22/2021 Lampiran VI & VIII"},
    {t:"Tetapkan rona lingkungan awal melalui pengukuran — air, udara, kebisingan — dicatat per lokasi/STA dengan foto, agar kepatuhan pascakonstruksi dapat dibuktikan terhadap titik awal yang sahih",ref:"Permen PUPR 10/2021 Lampiran G"},
    {t:"Untuk AMDAL: susun Formulir Kerangka Acuan → ANDAL → RKL-RPL, lalu ajukan uji kelayakan oleh Tim Uji Kelayakan Lingkungan Hidup (TUK) untuk memperoleh Persetujuan Kelayakan Lingkungan Hidup",ref:"PP 22/2021 — AMDAL"},
    {t:"Untuk UKL-UPL: susun formulir standar dan peroleh Persetujuan Pernyataan Kesanggupan Pengelolaan Lingkungan Hidup (PKPLH); untuk SPPL cukup registrasi surat pernyataan",ref:"PP 22/2021 — UKL-UPL / SPPL"},
    {t:"Peroleh Persetujuan Teknis (PERTEK) untuk setiap aliran yang diatur: pembuangan air limbah, emisi udara, pengelolaan limbah B3, dan/atau pembuangan ke laut — Rincian Teknis memadai untuk limbah nonbahan berbahaya",ref:"PP 22/2021 — Persetujuan Teknis"},
    {t:"Rancang pengendalian buangan dan emisi agar lingkungan penerima tetap dalam batas kelasnya — uji efluen terhadap tabel sungai/danau sesuai kelas yang ditetapkan, dan emisi cerobong/fugitif terhadap baku mutu udara ambien",ref:"Lampiran VI & VII (tabel pada parameter di bawah)"},
    {t:"Amankan Persetujuan Lingkungan sebelum Perizinan Berusaha — persetujuan lingkungan merupakan prasyarat izin usaha/operasi, bukan alur kerja paralel",ref:"PP 22/2021 jo. UU 11/2020"},
    {t:"Bawa komitmen RKL-RPL atau UKL-UPL ke dalam dokumen konstruksi: RKPPL pada SMKK wajib mengakomodasi dan menjabarkan setiap klausul, dan RMLLP wajib mencakup dampak terkait lalu lintas",ref:"Permen PUPR 10/2021 Lampiran G & H"},
    {t:"Lakukan pemantauan selama konstruksi dan operasi pada frekuensi yang ditetapkan dalam persetujuan — ambil sampel air, udara, dan kebisingan terhadap batas Lampiran VI/VII/VIII, catat hasilnya, dan laporkan berkala kepada instansi penerbit",ref:"PP 22/2021 — pemantauan RKL-RPL"},
    {t:"Verifikasi kepatuhan operasional dan peroleh SLO (Surat Kelayakan Operasional) yang menyatakan ketentuan PERTEK telah dipenuhi; pelihara berkas bukti untuk inspeksi dan audit",ref:"PP 22/2021 — SLO"}],
   alt:"🇺🇸 Amerika Serikat: Environmental Assessment / Environmental Impact Statement berdasarkan NEPA, dengan izin NPDES untuk pembuangan (CWA) dan izin Title V / NSR untuk emisi (CAA); air larian konstruksi di bawah CGP dengan SWPPP. 🇨🇳 Tiongkok: 环境影响评价 (EIA) berupa laporan/formulir/registrasi menurut jenjang dampak, disetujui oleh dinas ekologi dan lingkungan, 排污许可证 (izin pembuangan polutan), serta 三同时 — fasilitas pengendalian pencemaran dirancang, dibangun, dan dioperasikan bersamaan dengan pekerjaan utama; baku mutu ambien GB 3095-2012 (udara) dan GB 3838-2002 (air permukaan)."}},

hse:{icon:"🦺",
 en:{title:"Construction Safety (SMKK / HSE) Implementation Procedure",
   standard:"Permen PUPR 10/2021 — Pedoman SMKK · UU 2/2017 · ISO 45001 · OSHA 29 CFR 1926 · GB 50656-2011",
   steps:[
    {t:"Design stage — the design consultant prepares the Rancangan Konseptual SMKK: hazard identification against the DED, the ITP, environmental and traffic recommendations, and the O&M safety guide",ref:"Permen PUPR 10/2021 Lampiran C"},
    {t:"Identify hazards for every work activity (routine and non-routine) derived from the actual construction method, using multi-risk analysis across 5 receptors: workers, equipment, material, public and the environment",ref:"Lampiran C.6 & D — IBPRP, Tabel 5 & 6"},
    {t:"Score each hazard TR = K × A (Kekerapan × Keparahan) and determine the Construction Safety Risk Level — Kecil, Sedang or Besar",ref:"Lampiran C.6, Tabel 5"},
    {t:"Issue the signed Pernyataan Penetapan Tingkat Risiko Keselamatan Konstruksi (package name, engineer's estimate, location, declared risk level)",ref:"Lampiran C.8"},
    {t:"Apply the control hierarchy in order — eliminasi → substitusi → rekayasa teknis → pengendalian administratif → APD/APK — then re-assess the residual risk and add further controls if needed",ref:"Lampiran D.2 element 2"},
    {t:"Size the safety organisation to the risk level: risiko kecil → UKK function held by the top project leader; risiko sedang/besar → a separate Pimpinan UKK plus Ahli Keselamatan Konstruksi / Ahli K3 Konstruksi, coordinators, P3K, emergency, flagman, health and QA personnel",ref:"Lampiran A & D — Diagram 1.1/1.2, Tabel 8"},
    {t:"Build the RKK on the 5 elements: (1) leadership & worker participation, (2) planning/IBPRP & targets, (3) support — resources, competence, awareness, communication, documented information and the SMKK cost with its 9 components, (4) operation, (5) performance evaluation",ref:"Lampiran D.2"},
    {t:"Price the SMKK implementation cost as a separate, non-competed item (min. 9 components), outside the expert-remuneration budget",ref:"Permen PUPR 10/2021 batang tubuh + Lampiran Biaya SMKK"},
    {t:"Prepare the companion documents and cross-link them: RMPK (method + ITP), RKPPL (environment), RMLLP (traffic), Program Mutu for consultancy",ref:"Lampiran E, F, G, H"},
    {t:"Execute operational control: AKK plus a special work permit for every medium/large-risk activity, plant fitness permits and operator licences, PPE procedures, subcontractor control, worker social protection and health checks, 5R housekeeping and waste management, plus a stop-work rule for dangerous conditions",ref:"Lampiran D.2 element 4"},
    {t:"Run safety communication continuously — safety induction for every new worker, toolbox meetings, and the scheduled consultation/communication programme",ref:"Lampiran D.2 element 3.4"},
    {t:"Evaluate and improve: scheduled inspections against a checklist, audit against the RKK criteria, compliance evaluation, management review, incident/dangerous-occurrence/occupational-disease investigation, and corrective action",ref:"Lampiran D.2 element 5 & I (Laporan Pelaksanaan)"}],
   alt:"🇺🇸 OSHA 29 CFR 1926 + ISO 45001: site-specific safety plan, Job Hazard Analysis per task, competent-person inspections, permit-to-work for confined space/hot work/excavation, LOTO, fall protection above 6 ft (1.8 m), and recordkeeping on OSHA 300 logs. 🇨🇳 GB 50656-2011 + JGJ 59-2011: 安全生产管理体系 with 专职安全生产管理人员 staffed by contract value and floor area, 危险源辨识 scoring, 专项施工方案 with expert review for 危险性较大的分部分项工程 (deep excavation, formwork support, lifting, scaffolding above threshold), and the statutory non-negotiable 安全文明施工费."},
 zh:{title:"施工安全（SMKK / HSE）实施流程",
   standard:"部长条例 PUPR 10/2021 — SMKK 指南 · 印尼建筑服务法 UU 2/2017 · ISO 45001 · OSHA 29 CFR 1926 · GB 50656-2011",
   steps:[
    {t:"设计阶段 — 由设计咨询方编制 SMKK 概念设计：针对施工图的危险源辨识、检验试验计划（ITP）、环境与交通建议、运维安全指南",ref:"部长条例 PUPR 10/2021 附件 C"},
    {t:"依据实际施工方法，对全部作业活动（例行与非例行）进行危险源辨识，按 5 类受体开展多风险分析：作业人员、设备、材料、公众、生态环境",ref:"附件 C.6 与 D — IBPRP，表 5 与表 6"},
    {t:"逐项计算 TR = K × A（发生频率 × 严重程度），确定施工安全风险等级 — 小、中或大",ref:"附件 C.6，表 5"},
    {t:"签发《施工安全风险等级确定声明》（工程包名称、设计概算、地点、确定的风险等级）",ref:"附件 C.8"},
    {t:"按层级顺序实施控制 — 消除 → 替代 → 工程技术控制 → 管理控制 → APD/APK，随后重新评价剩余风险，必要时追加措施",ref:"附件 D.2 要素 2"},
    {t:"按风险等级配置安全组织：小风险 → UKK 职能由项目最高负责人兼任；中/大风险 → 单设 UKK 负责人，并配施工安全专家 / K3 专家、协调员、急救员、应急人员、交通指挥员、医护及质量保证人员",ref:"附件 A 与 D — 图 1.1/1.2、表 8"},
    {t:"按五大要素编制 RKK：(1) 领导力与员工参与，(2) 策划/IBPRP 与目标方案，(3) 支持 — 资源、能力、意识、沟通、文件化信息及含 9 项组成的 SMKK 费用，(4) 运行，(5) 绩效评价",ref:"附件 D.2"},
    {t:"将 SMKK 实施费用单列计价、不参与竞价（至少 9 项组成），且不计入专家酬金预算",ref:"部长条例 PUPR 10/2021 正文 + SMKK 费用附件"},
    {t:"编制并相互衔接配套文件：RMPK（施工方法 + ITP）、RKPPL（环境）、RMLLP（交通）、咨询服务的质量纲要",ref:"附件 E、F、G、H"},
    {t:"落实运行控制：中/大风险作业须编制 AKK 并办理专项作业许可；设备准用证与操作人员执照；个体防护程序；分包商控制；作业人员社会保障与健康检查；5R 现场整理与废弃物管理；发现危险状况时执行停工程序",ref:"附件 D.2 要素 4"},
    {t:"持续开展安全沟通 — 对每名新进人员进行安全交底（safety induction）、班前会（toolbox meeting）及既定的协商沟通计划",ref:"附件 D.2 要素 3.4"},
    {t:"评价与改进：按计划与检查表巡检、按 RKK 准则审核、合规性评价、管理评审、事故/危险事件/职业病调查及纠正措施",ref:"附件 D.2 要素 5 与附件 I（实施报告）"}],
   alt:"🇺🇸 OSHA 29 CFR 1926 + ISO 45001：现场专项安全计划、逐项作业的 JHA、主管人员巡检、受限空间/动火/开挖作业许可、上锁挂牌（LOTO）、6 ft（1.8 m）以上高处作业防坠落，并按 OSHA 300 记录台账。🇨🇳 GB 50656-2011 + JGJ 59-2011：安全生产管理体系，按合同额与建筑面积配备专职安全生产管理人员，危险源辨识评分，危险性较大的分部分项工程（深基坑、模板支撑、起重吊装、超规模脚手架）须编制专项施工方案并经专家论证，并计取法定不可竞价的安全文明施工费。"}},

fire:{icon:"🔥",
 en:{title:"Fire Protection Design Procedure",
   standard:"SNI 03-1735/1736-2000 · Permen PUPR 26/2008 · GB 50016 · NFPA/IBC",
   steps:[
    {t:"Classify occupancy & determine building class, height and floor area",ref:"Permen 26/2008 §1 / IBC Ch.3"},
    {t:"Set construction type and required fire-resistance rating (TKA) of structural elements",ref:"SNI 1736 / Permen 26 Tabel 1 / GB 50016 §3.2"},
    {t:"Compartmentation: max compartment areas, fire walls, protection of openings",ref:"GB 50016 §5 / SNI 1736"},
    {t:"Means of egress: number of exits, travel distance, exit widths, dead-end ≤ 6 m",ref:"Permen 26 §3.11 / GB 50016 §5.5 / NFPA 101"},
    {t:"Fire apparatus access roads & hardstanding by building volume; access openings",ref:"SNI 1735 §4 & §6"},
    {t:"Water supply & hydrants (yard hydrant ≤ 50 m, ≥ 38 L/s residential)",ref:"SNI 1735 §5 / GB 50974"},
    {t:"Active systems: detection & alarm, sprinklers (density by hazard), standpipes, extinguishers",ref:"NFPA 13/14/72 / SNI 03-3989 / GB 50084"},
    {t:"Smoke management, emergency lighting/power, firefighter lift & lobby",ref:"GB 51251 / Permen 26 §6 / IBC Ch.9"}],
   alt:"🇨🇳 GB 50016-2014 is the consolidated Chinese building fire code (耐火等级, 防火分区, 安全疏散, 消防车道). 🇺🇸 IBC + IFC + NFPA series; the Indonesian SNI 17xx series mirrors NFPA/BCA provisions."},
 zh:{title:"消防设计流程",
   standard:"SNI 03-1735/1736-2000 · 部长条例 26/2008 · GB 50016 · NFPA/IBC",
   steps:[
    {t:"确定使用功能、建筑类别、高度与楼层面积",ref:"条例 26/2008 §1 / IBC 第3章"},
    {t:"确定构造类型与结构构件所需耐火极限（TKA）",ref:"SNI 1736 / 条例 26 表1 / GB 50016 §3.2"},
    {t:"防火分隔：最大防火分区面积、防火墙、洞口保护",ref:"GB 50016 §5 / SNI 1736"},
    {t:"安全疏散：安全出口数量、疏散距离、出口宽度、袋形走道 ≤ 6 m",ref:"条例 26 §3.11 / GB 50016 §5.5 / NFPA 101"},
    {t:"按建筑体积设消防车道与登高场地；消防扑救口",ref:"SNI 1735 §4 与 §6"},
    {t:"消防给水与消火栓（室外消火栓 ≤ 50 m，住宅 ≥ 38 L/s）",ref:"SNI 1735 §5 / GB 50974"},
    {t:"主动系统：探测报警、自动喷水（按危险级喷水强度）、消火栓系统、灭火器",ref:"NFPA 13/14/72 / SNI 03-3989 / GB 50084"},
    {t:"防排烟、应急照明/电源、消防电梯与前室",ref:"GB 51251 / 条例 26 §6 / IBC 第9章"}],
   alt:"🇨🇳 GB 50016-2014 为中国综合建筑防火规范（耐火等级、防火分区、安全疏散、消防车道）。🇺🇸 IBC + IFC + NFPA 系列；印尼 SNI 17xx 系列对标 NFPA/BCA。"}}

};
